/*
Octo Payment API

Testing TransactionManagementAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package octoapi

import (
	"context"
	"testing"

	openapiclient "github.com/iota-uz/octo"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_octoapi_TransactionManagementAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TransactionManagementAPIService RefundPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.TransactionManagementAPI.RefundPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransactionManagementAPIService SetAcceptPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.TransactionManagementAPI.SetAcceptPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
