/*
Octo Payment API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package octoapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)

type PaymentsAPI interface {

	/*
		PreparePaymentPost Initiate or check payment

		Initiates a new payment or checks the status of an existing one using `shop_transaction_id`.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return PaymentsAPIPreparePaymentPostRequest
	*/
	PreparePaymentPost(ctx context.Context) PaymentsAPIPreparePaymentPostRequest

	// PreparePaymentPostExecute executes the request
	//  @return PreparePaymentResponse
	PreparePaymentPostExecute(r PaymentsAPIPreparePaymentPostRequest) (*PreparePaymentResponse, *http.Response, error)
}

// PaymentsAPIService PaymentsAPI service
type PaymentsAPIService service

type PaymentsAPIPreparePaymentPostRequest struct {
	ctx                   context.Context
	ApiService            PaymentsAPI
	preparePaymentRequest *PreparePaymentRequest
}

func (r PaymentsAPIPreparePaymentPostRequest) PreparePaymentRequest(preparePaymentRequest PreparePaymentRequest) PaymentsAPIPreparePaymentPostRequest {
	r.preparePaymentRequest = &preparePaymentRequest
	return r
}

func (r PaymentsAPIPreparePaymentPostRequest) Execute() (*PreparePaymentResponse, *http.Response, error) {
	return r.ApiService.PreparePaymentPostExecute(r)
}

/*
PreparePaymentPost Initiate or check payment

Initiates a new payment or checks the status of an existing one using `shop_transaction_id`.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return PaymentsAPIPreparePaymentPostRequest
*/
func (a *PaymentsAPIService) PreparePaymentPost(ctx context.Context) PaymentsAPIPreparePaymentPostRequest {
	return PaymentsAPIPreparePaymentPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return PreparePaymentResponse
func (a *PaymentsAPIService) PreparePaymentPostExecute(r PaymentsAPIPreparePaymentPostRequest) (*PreparePaymentResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PreparePaymentResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PaymentsAPIService.PreparePaymentPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/prepare_payment"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.preparePaymentRequest == nil {
		return localVarReturnValue, nil, reportError("preparePaymentRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.preparePaymentRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
