/*
Octo Payment API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package octoapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)

type TransactionManagementAPI interface {

	/*
		RefundPost Refund a payment

		Initiates a refund for a completed transaction.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return TransactionManagementAPIRefundPostRequest
	*/
	RefundPost(ctx context.Context) TransactionManagementAPIRefundPostRequest

	// RefundPostExecute executes the request
	//  @return RefundResponse
	RefundPostExecute(r TransactionManagementAPIRefundPostRequest) (*RefundResponse, *http.Response, error)

	/*
		SetAcceptPost Confirm or cancel a transaction

		Captures or cancels a previously authorized transaction.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return TransactionManagementAPISetAcceptPostRequest
	*/
	SetAcceptPost(ctx context.Context) TransactionManagementAPISetAcceptPostRequest

	// SetAcceptPostExecute executes the request
	//  @return SetAcceptResponse
	SetAcceptPostExecute(r TransactionManagementAPISetAcceptPostRequest) (*SetAcceptResponse, *http.Response, error)
}

// TransactionManagementAPIService TransactionManagementAPI service
type TransactionManagementAPIService service

type TransactionManagementAPIRefundPostRequest struct {
	ctx           context.Context
	ApiService    TransactionManagementAPI
	refundRequest *RefundRequest
}

func (r TransactionManagementAPIRefundPostRequest) RefundRequest(refundRequest RefundRequest) TransactionManagementAPIRefundPostRequest {
	r.refundRequest = &refundRequest
	return r
}

func (r TransactionManagementAPIRefundPostRequest) Execute() (*RefundResponse, *http.Response, error) {
	return r.ApiService.RefundPostExecute(r)
}

/*
RefundPost Refund a payment

Initiates a refund for a completed transaction.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return TransactionManagementAPIRefundPostRequest
*/
func (a *TransactionManagementAPIService) RefundPost(ctx context.Context) TransactionManagementAPIRefundPostRequest {
	return TransactionManagementAPIRefundPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return RefundResponse
func (a *TransactionManagementAPIService) RefundPostExecute(r TransactionManagementAPIRefundPostRequest) (*RefundResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *RefundResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TransactionManagementAPIService.RefundPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/refund"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.refundRequest == nil {
		return localVarReturnValue, nil, reportError("refundRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.refundRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type TransactionManagementAPISetAcceptPostRequest struct {
	ctx              context.Context
	ApiService       TransactionManagementAPI
	setAcceptRequest *SetAcceptRequest
}

func (r TransactionManagementAPISetAcceptPostRequest) SetAcceptRequest(setAcceptRequest SetAcceptRequest) TransactionManagementAPISetAcceptPostRequest {
	r.setAcceptRequest = &setAcceptRequest
	return r
}

func (r TransactionManagementAPISetAcceptPostRequest) Execute() (*SetAcceptResponse, *http.Response, error) {
	return r.ApiService.SetAcceptPostExecute(r)
}

/*
SetAcceptPost Confirm or cancel a transaction

Captures or cancels a previously authorized transaction.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return TransactionManagementAPISetAcceptPostRequest
*/
func (a *TransactionManagementAPIService) SetAcceptPost(ctx context.Context) TransactionManagementAPISetAcceptPostRequest {
	return TransactionManagementAPISetAcceptPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return SetAcceptResponse
func (a *TransactionManagementAPIService) SetAcceptPostExecute(r TransactionManagementAPISetAcceptPostRequest) (*SetAcceptResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *SetAcceptResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TransactionManagementAPIService.SetAcceptPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/set_accept"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.setAcceptRequest == nil {
		return localVarReturnValue, nil, reportError("setAcceptRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.setAcceptRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
