/*
Octo Payment API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package octoapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)

type IntegrationAPI interface {

	/*
		CallbackPost Handle Octo callback

		Callback sent by Octo when a transaction needs confirmation by the merchant.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return IntegrationAPICallbackPostRequest
	*/
	CallbackPost(ctx context.Context) IntegrationAPICallbackPostRequest

	// CallbackPostExecute executes the request
	//  @return CallbackResponse
	CallbackPostExecute(r IntegrationAPICallbackPostRequest) (*CallbackResponse, *http.Response, error)

	/*
		NotificationPost Receive notification from Octo

		Notification sent by Octo about status changes of a payment.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return IntegrationAPINotificationPostRequest
	*/
	NotificationPost(ctx context.Context) IntegrationAPINotificationPostRequest

	// NotificationPostExecute executes the request
	NotificationPostExecute(r IntegrationAPINotificationPostRequest) (*http.Response, error)
}

// IntegrationAPIService IntegrationAPI service
type IntegrationAPIService service

type IntegrationAPICallbackPostRequest struct {
	ctx             context.Context
	ApiService      IntegrationAPI
	callbackRequest *CallbackRequest
}

func (r IntegrationAPICallbackPostRequest) CallbackRequest(callbackRequest CallbackRequest) IntegrationAPICallbackPostRequest {
	r.callbackRequest = &callbackRequest
	return r
}

func (r IntegrationAPICallbackPostRequest) Execute() (*CallbackResponse, *http.Response, error) {
	return r.ApiService.CallbackPostExecute(r)
}

/*
CallbackPost Handle Octo callback

Callback sent by Octo when a transaction needs confirmation by the merchant.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return IntegrationAPICallbackPostRequest
*/
func (a *IntegrationAPIService) CallbackPost(ctx context.Context) IntegrationAPICallbackPostRequest {
	return IntegrationAPICallbackPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CallbackResponse
func (a *IntegrationAPIService) CallbackPostExecute(r IntegrationAPICallbackPostRequest) (*CallbackResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CallbackResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "IntegrationAPIService.CallbackPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/callback"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.callbackRequest == nil {
		return localVarReturnValue, nil, reportError("callbackRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.callbackRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type IntegrationAPINotificationPostRequest struct {
	ctx                 context.Context
	ApiService          IntegrationAPI
	notificationRequest *NotificationRequest
}

func (r IntegrationAPINotificationPostRequest) NotificationRequest(notificationRequest NotificationRequest) IntegrationAPINotificationPostRequest {
	r.notificationRequest = &notificationRequest
	return r
}

func (r IntegrationAPINotificationPostRequest) Execute() (*http.Response, error) {
	return r.ApiService.NotificationPostExecute(r)
}

/*
NotificationPost Receive notification from Octo

Notification sent by Octo about status changes of a payment.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return IntegrationAPINotificationPostRequest
*/
func (a *IntegrationAPIService) NotificationPost(ctx context.Context) IntegrationAPINotificationPostRequest {
	return IntegrationAPINotificationPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
func (a *IntegrationAPIService) NotificationPostExecute(r IntegrationAPINotificationPostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodPost
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "IntegrationAPIService.NotificationPost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/notification"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.notificationRequest == nil {
		return nil, reportError("notificationRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.notificationRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
