/*
Octo Payment API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package octoapi

import (
	"encoding/json"
	"time"
)

// checks if the RefundSuccessResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefundSuccessResponseData{}

// RefundSuccessResponseData struct for RefundSuccessResponseData
type RefundSuccessResponseData struct {
	OctoPaymentUUID *string    `form:"octo_payment_UUID" json:"octo_payment_UUID,omitempty"`
	RefundId        *string    `form:"refund_id" json:"refund_id,omitempty"`
	RefundTime      *time.Time `form:"refund_time" json:"refund_time,omitempty"`
	Status          *string    `form:"status" json:"status,omitempty"`
}

// NewRefundSuccessResponseData instantiates a new RefundSuccessResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefundSuccessResponseData() *RefundSuccessResponseData {
	this := RefundSuccessResponseData{}
	return &this
}

// NewRefundSuccessResponseDataWithDefaults instantiates a new RefundSuccessResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefundSuccessResponseDataWithDefaults() *RefundSuccessResponseData {
	this := RefundSuccessResponseData{}
	return &this
}

// GetOctoPaymentUUID returns the OctoPaymentUUID field value if set, zero value otherwise.
func (o *RefundSuccessResponseData) GetOctoPaymentUUID() string {
	if o == nil || IsNil(o.OctoPaymentUUID) {
		var ret string
		return ret
	}
	return *o.OctoPaymentUUID
}

// GetOctoPaymentUUIDOk returns a tuple with the OctoPaymentUUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundSuccessResponseData) GetOctoPaymentUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.OctoPaymentUUID) {
		return nil, false
	}
	return o.OctoPaymentUUID, true
}

// HasOctoPaymentUUID returns a boolean if a field has been set.
func (o *RefundSuccessResponseData) HasOctoPaymentUUID() bool {
	if o != nil && !IsNil(o.OctoPaymentUUID) {
		return true
	}

	return false
}

// SetOctoPaymentUUID gets a reference to the given string and assigns it to the OctoPaymentUUID field.
func (o *RefundSuccessResponseData) SetOctoPaymentUUID(v string) {
	o.OctoPaymentUUID = &v
}

// GetRefundId returns the RefundId field value if set, zero value otherwise.
func (o *RefundSuccessResponseData) GetRefundId() string {
	if o == nil || IsNil(o.RefundId) {
		var ret string
		return ret
	}
	return *o.RefundId
}

// GetRefundIdOk returns a tuple with the RefundId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundSuccessResponseData) GetRefundIdOk() (*string, bool) {
	if o == nil || IsNil(o.RefundId) {
		return nil, false
	}
	return o.RefundId, true
}

// HasRefundId returns a boolean if a field has been set.
func (o *RefundSuccessResponseData) HasRefundId() bool {
	if o != nil && !IsNil(o.RefundId) {
		return true
	}

	return false
}

// SetRefundId gets a reference to the given string and assigns it to the RefundId field.
func (o *RefundSuccessResponseData) SetRefundId(v string) {
	o.RefundId = &v
}

// GetRefundTime returns the RefundTime field value if set, zero value otherwise.
func (o *RefundSuccessResponseData) GetRefundTime() time.Time {
	if o == nil || IsNil(o.RefundTime) {
		var ret time.Time
		return ret
	}
	return *o.RefundTime
}

// GetRefundTimeOk returns a tuple with the RefundTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundSuccessResponseData) GetRefundTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RefundTime) {
		return nil, false
	}
	return o.RefundTime, true
}

// HasRefundTime returns a boolean if a field has been set.
func (o *RefundSuccessResponseData) HasRefundTime() bool {
	if o != nil && !IsNil(o.RefundTime) {
		return true
	}

	return false
}

// SetRefundTime gets a reference to the given time.Time and assigns it to the RefundTime field.
func (o *RefundSuccessResponseData) SetRefundTime(v time.Time) {
	o.RefundTime = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RefundSuccessResponseData) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundSuccessResponseData) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RefundSuccessResponseData) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *RefundSuccessResponseData) SetStatus(v string) {
	o.Status = &v
}

func (o RefundSuccessResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefundSuccessResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OctoPaymentUUID) {
		toSerialize["octo_payment_UUID"] = o.OctoPaymentUUID
	}
	if !IsNil(o.RefundId) {
		toSerialize["refund_id"] = o.RefundId
	}
	if !IsNil(o.RefundTime) {
		toSerialize["refund_time"] = o.RefundTime
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableRefundSuccessResponseData struct {
	value *RefundSuccessResponseData
	isSet bool
}

func (v NullableRefundSuccessResponseData) Get() *RefundSuccessResponseData {
	return v.value
}

func (v *NullableRefundSuccessResponseData) Set(val *RefundSuccessResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableRefundSuccessResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableRefundSuccessResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefundSuccessResponseData(val *RefundSuccessResponseData) *NullableRefundSuccessResponseData {
	return &NullableRefundSuccessResponseData{value: val, isSet: true}
}

func (v NullableRefundSuccessResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefundSuccessResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
