/*
Octo Payment API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package octoapi

import (
	"encoding/json"
)

// checks if the RefundSuccessResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefundSuccessResponse{}

// RefundSuccessResponse struct for RefundSuccessResponse
type RefundSuccessResponse struct {
	Error                   *int32                     `form:"error" json:"error,omitempty"`
	ErrMessage              *string                    `form:"errMessage" json:"errMessage,omitempty"`
	Data                    *RefundSuccessResponseData `form:"data" json:"data,omitempty"`
	ApiMessageForDevelopers *string                    `form:"apiMessageForDevelopers" json:"apiMessageForDevelopers,omitempty"`
}

// NewRefundSuccessResponse instantiates a new RefundSuccessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefundSuccessResponse() *RefundSuccessResponse {
	this := RefundSuccessResponse{}
	return &this
}

// NewRefundSuccessResponseWithDefaults instantiates a new RefundSuccessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefundSuccessResponseWithDefaults() *RefundSuccessResponse {
	this := RefundSuccessResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *RefundSuccessResponse) GetError() int32 {
	if o == nil || IsNil(o.Error) {
		var ret int32
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundSuccessResponse) GetErrorOk() (*int32, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *RefundSuccessResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given int32 and assigns it to the Error field.
func (o *RefundSuccessResponse) SetError(v int32) {
	o.Error = &v
}

// GetErrMessage returns the ErrMessage field value if set, zero value otherwise.
func (o *RefundSuccessResponse) GetErrMessage() string {
	if o == nil || IsNil(o.ErrMessage) {
		var ret string
		return ret
	}
	return *o.ErrMessage
}

// GetErrMessageOk returns a tuple with the ErrMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundSuccessResponse) GetErrMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrMessage) {
		return nil, false
	}
	return o.ErrMessage, true
}

// HasErrMessage returns a boolean if a field has been set.
func (o *RefundSuccessResponse) HasErrMessage() bool {
	if o != nil && !IsNil(o.ErrMessage) {
		return true
	}

	return false
}

// SetErrMessage gets a reference to the given string and assigns it to the ErrMessage field.
func (o *RefundSuccessResponse) SetErrMessage(v string) {
	o.ErrMessage = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *RefundSuccessResponse) GetData() RefundSuccessResponseData {
	if o == nil || IsNil(o.Data) {
		var ret RefundSuccessResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundSuccessResponse) GetDataOk() (*RefundSuccessResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *RefundSuccessResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given RefundSuccessResponseData and assigns it to the Data field.
func (o *RefundSuccessResponse) SetData(v RefundSuccessResponseData) {
	o.Data = &v
}

// GetApiMessageForDevelopers returns the ApiMessageForDevelopers field value if set, zero value otherwise.
func (o *RefundSuccessResponse) GetApiMessageForDevelopers() string {
	if o == nil || IsNil(o.ApiMessageForDevelopers) {
		var ret string
		return ret
	}
	return *o.ApiMessageForDevelopers
}

// GetApiMessageForDevelopersOk returns a tuple with the ApiMessageForDevelopers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundSuccessResponse) GetApiMessageForDevelopersOk() (*string, bool) {
	if o == nil || IsNil(o.ApiMessageForDevelopers) {
		return nil, false
	}
	return o.ApiMessageForDevelopers, true
}

// HasApiMessageForDevelopers returns a boolean if a field has been set.
func (o *RefundSuccessResponse) HasApiMessageForDevelopers() bool {
	if o != nil && !IsNil(o.ApiMessageForDevelopers) {
		return true
	}

	return false
}

// SetApiMessageForDevelopers gets a reference to the given string and assigns it to the ApiMessageForDevelopers field.
func (o *RefundSuccessResponse) SetApiMessageForDevelopers(v string) {
	o.ApiMessageForDevelopers = &v
}

func (o RefundSuccessResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefundSuccessResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.ErrMessage) {
		toSerialize["errMessage"] = o.ErrMessage
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.ApiMessageForDevelopers) {
		toSerialize["apiMessageForDevelopers"] = o.ApiMessageForDevelopers
	}
	return toSerialize, nil
}

type NullableRefundSuccessResponse struct {
	value *RefundSuccessResponse
	isSet bool
}

func (v NullableRefundSuccessResponse) Get() *RefundSuccessResponse {
	return v.value
}

func (v *NullableRefundSuccessResponse) Set(val *RefundSuccessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRefundSuccessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRefundSuccessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefundSuccessResponse(val *RefundSuccessResponse) *NullableRefundSuccessResponse {
	return &NullableRefundSuccessResponse{value: val, isSet: true}
}

func (v NullableRefundSuccessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefundSuccessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
