/*
Octo Payment API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package octoapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BasketItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BasketItem{}

// BasketItem struct for BasketItem
type BasketItem struct {
	PositionDesc string  `form:"position_desc" json:"position_desc"`
	Count        int32   `form:"count" json:"count"`
	Price        float32 `form:"price" json:"price"`
	Spic         *string `form:"spic" json:"spic,omitempty"`
}

type _BasketItem BasketItem

// NewBasketItem instantiates a new BasketItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBasketItem(positionDesc string, count int32, price float32) *BasketItem {
	this := BasketItem{}
	this.PositionDesc = positionDesc
	this.Count = count
	this.Price = price
	return &this
}

// NewBasketItemWithDefaults instantiates a new BasketItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBasketItemWithDefaults() *BasketItem {
	this := BasketItem{}
	return &this
}

// GetPositionDesc returns the PositionDesc field value
func (o *BasketItem) GetPositionDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PositionDesc
}

// GetPositionDescOk returns a tuple with the PositionDesc field value
// and a boolean to check if the value has been set.
func (o *BasketItem) GetPositionDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PositionDesc, true
}

// SetPositionDesc sets field value
func (o *BasketItem) SetPositionDesc(v string) {
	o.PositionDesc = v
}

// GetCount returns the Count field value
func (o *BasketItem) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *BasketItem) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *BasketItem) SetCount(v int32) {
	o.Count = v
}

// GetPrice returns the Price field value
func (o *BasketItem) GetPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *BasketItem) GetPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *BasketItem) SetPrice(v float32) {
	o.Price = v
}

// GetSpic returns the Spic field value if set, zero value otherwise.
func (o *BasketItem) GetSpic() string {
	if o == nil || IsNil(o.Spic) {
		var ret string
		return ret
	}
	return *o.Spic
}

// GetSpicOk returns a tuple with the Spic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasketItem) GetSpicOk() (*string, bool) {
	if o == nil || IsNil(o.Spic) {
		return nil, false
	}
	return o.Spic, true
}

// HasSpic returns a boolean if a field has been set.
func (o *BasketItem) HasSpic() bool {
	if o != nil && !IsNil(o.Spic) {
		return true
	}

	return false
}

// SetSpic gets a reference to the given string and assigns it to the Spic field.
func (o *BasketItem) SetSpic(v string) {
	o.Spic = &v
}

func (o BasketItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BasketItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["position_desc"] = o.PositionDesc
	toSerialize["count"] = o.Count
	toSerialize["price"] = o.Price
	if !IsNil(o.Spic) {
		toSerialize["spic"] = o.Spic
	}
	return toSerialize, nil
}

func (o *BasketItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"position_desc",
		"count",
		"price",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBasketItem := _BasketItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBasketItem)

	if err != nil {
		return err
	}

	*o = BasketItem(varBasketItem)

	return err
}

type NullableBasketItem struct {
	value *BasketItem
	isSet bool
}

func (v NullableBasketItem) Get() *BasketItem {
	return v.value
}

func (v *NullableBasketItem) Set(val *BasketItem) {
	v.value = val
	v.isSet = true
}

func (v NullableBasketItem) IsSet() bool {
	return v.isSet
}

func (v *NullableBasketItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBasketItem(val *BasketItem) *NullableBasketItem {
	return &NullableBasketItem{value: val, isSet: true}
}

func (v NullableBasketItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBasketItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
