/*
Octo Payment API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package octoapi

import (
	"encoding/json"
)

// checks if the RefundResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefundResponse{}

// RefundResponse struct for RefundResponse
type RefundResponse struct {
	Error                   *int32                     `form:"error" json:"error,omitempty"`
	ErrMessage              *string                    `form:"errMessage" json:"errMessage,omitempty"`
	ErrorMessage            *string                    `form:"errorMessage" json:"errorMessage,omitempty"`
	ApiMessageForDevelopers *string                    `form:"apiMessageForDevelopers" json:"apiMessageForDevelopers,omitempty"`
	Data                    *RefundSuccessResponseData `form:"data" json:"data,omitempty"`
}

// NewRefundResponse instantiates a new RefundResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefundResponse() *RefundResponse {
	this := RefundResponse{}
	return &this
}

// NewRefundResponseWithDefaults instantiates a new RefundResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefundResponseWithDefaults() *RefundResponse {
	this := RefundResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *RefundResponse) GetError() int32 {
	if o == nil || IsNil(o.Error) {
		var ret int32
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundResponse) GetErrorOk() (*int32, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *RefundResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given int32 and assigns it to the Error field.
func (o *RefundResponse) SetError(v int32) {
	o.Error = &v
}

// GetErrMessage returns the ErrMessage field value if set, zero value otherwise.
func (o *RefundResponse) GetErrMessage() string {
	if o == nil || IsNil(o.ErrMessage) {
		var ret string
		return ret
	}
	return *o.ErrMessage
}

// GetErrMessageOk returns a tuple with the ErrMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundResponse) GetErrMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrMessage) {
		return nil, false
	}
	return o.ErrMessage, true
}

// HasErrMessage returns a boolean if a field has been set.
func (o *RefundResponse) HasErrMessage() bool {
	if o != nil && !IsNil(o.ErrMessage) {
		return true
	}

	return false
}

// SetErrMessage gets a reference to the given string and assigns it to the ErrMessage field.
func (o *RefundResponse) SetErrMessage(v string) {
	o.ErrMessage = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *RefundResponse) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundResponse) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *RefundResponse) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *RefundResponse) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetApiMessageForDevelopers returns the ApiMessageForDevelopers field value if set, zero value otherwise.
func (o *RefundResponse) GetApiMessageForDevelopers() string {
	if o == nil || IsNil(o.ApiMessageForDevelopers) {
		var ret string
		return ret
	}
	return *o.ApiMessageForDevelopers
}

// GetApiMessageForDevelopersOk returns a tuple with the ApiMessageForDevelopers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundResponse) GetApiMessageForDevelopersOk() (*string, bool) {
	if o == nil || IsNil(o.ApiMessageForDevelopers) {
		return nil, false
	}
	return o.ApiMessageForDevelopers, true
}

// HasApiMessageForDevelopers returns a boolean if a field has been set.
func (o *RefundResponse) HasApiMessageForDevelopers() bool {
	if o != nil && !IsNil(o.ApiMessageForDevelopers) {
		return true
	}

	return false
}

// SetApiMessageForDevelopers gets a reference to the given string and assigns it to the ApiMessageForDevelopers field.
func (o *RefundResponse) SetApiMessageForDevelopers(v string) {
	o.ApiMessageForDevelopers = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *RefundResponse) GetData() RefundSuccessResponseData {
	if o == nil || IsNil(o.Data) {
		var ret RefundSuccessResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundResponse) GetDataOk() (*RefundSuccessResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *RefundResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given RefundSuccessResponseData and assigns it to the Data field.
func (o *RefundResponse) SetData(v RefundSuccessResponseData) {
	o.Data = &v
}

func (o RefundResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefundResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.ErrMessage) {
		toSerialize["errMessage"] = o.ErrMessage
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	if !IsNil(o.ApiMessageForDevelopers) {
		toSerialize["apiMessageForDevelopers"] = o.ApiMessageForDevelopers
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableRefundResponse struct {
	value *RefundResponse
	isSet bool
}

func (v NullableRefundResponse) Get() *RefundResponse {
	return v.value
}

func (v *NullableRefundResponse) Set(val *RefundResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRefundResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRefundResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefundResponse(val *RefundResponse) *NullableRefundResponse {
	return &NullableRefundResponse{value: val, isSet: true}
}

func (v NullableRefundResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefundResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
