/*
Octo Payment API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package octoapi

import (
	"encoding/json"
)

// checks if the SetAcceptSuccessResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetAcceptSuccessResponseData{}

// SetAcceptSuccessResponseData struct for SetAcceptSuccessResponseData
type SetAcceptSuccessResponseData struct {
	ShopTransactionId *string  `form:"shop_transaction_id" json:"shop_transaction_id,omitempty"`
	OctoPaymentUUID   *string  `form:"octo_payment_UUID" json:"octo_payment_UUID,omitempty"`
	Status            *string  `form:"status" json:"status,omitempty"`
	OctoPayUrl        *string  `form:"octo_pay_url" json:"octo_pay_url,omitempty"`
	TransferSum       *float64 `form:"transfer_sum" json:"transfer_sum,omitempty"`
	RefundedSum       *float64 `form:"refunded_sum" json:"refunded_sum,omitempty"`
	TotalSum          *float64 `form:"total_sum" json:"total_sum,omitempty"`
	PayedTime         *string  `form:"payed_time" json:"payed_time,omitempty"`
}

// NewSetAcceptSuccessResponseData instantiates a new SetAcceptSuccessResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetAcceptSuccessResponseData() *SetAcceptSuccessResponseData {
	this := SetAcceptSuccessResponseData{}
	return &this
}

// NewSetAcceptSuccessResponseDataWithDefaults instantiates a new SetAcceptSuccessResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetAcceptSuccessResponseDataWithDefaults() *SetAcceptSuccessResponseData {
	this := SetAcceptSuccessResponseData{}
	return &this
}

// GetShopTransactionId returns the ShopTransactionId field value if set, zero value otherwise.
func (o *SetAcceptSuccessResponseData) GetShopTransactionId() string {
	if o == nil || IsNil(o.ShopTransactionId) {
		var ret string
		return ret
	}
	return *o.ShopTransactionId
}

// GetShopTransactionIdOk returns a tuple with the ShopTransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetAcceptSuccessResponseData) GetShopTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.ShopTransactionId) {
		return nil, false
	}
	return o.ShopTransactionId, true
}

// HasShopTransactionId returns a boolean if a field has been set.
func (o *SetAcceptSuccessResponseData) HasShopTransactionId() bool {
	if o != nil && !IsNil(o.ShopTransactionId) {
		return true
	}

	return false
}

// SetShopTransactionId gets a reference to the given string and assigns it to the ShopTransactionId field.
func (o *SetAcceptSuccessResponseData) SetShopTransactionId(v string) {
	o.ShopTransactionId = &v
}

// GetOctoPaymentUUID returns the OctoPaymentUUID field value if set, zero value otherwise.
func (o *SetAcceptSuccessResponseData) GetOctoPaymentUUID() string {
	if o == nil || IsNil(o.OctoPaymentUUID) {
		var ret string
		return ret
	}
	return *o.OctoPaymentUUID
}

// GetOctoPaymentUUIDOk returns a tuple with the OctoPaymentUUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetAcceptSuccessResponseData) GetOctoPaymentUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.OctoPaymentUUID) {
		return nil, false
	}
	return o.OctoPaymentUUID, true
}

// HasOctoPaymentUUID returns a boolean if a field has been set.
func (o *SetAcceptSuccessResponseData) HasOctoPaymentUUID() bool {
	if o != nil && !IsNil(o.OctoPaymentUUID) {
		return true
	}

	return false
}

// SetOctoPaymentUUID gets a reference to the given string and assigns it to the OctoPaymentUUID field.
func (o *SetAcceptSuccessResponseData) SetOctoPaymentUUID(v string) {
	o.OctoPaymentUUID = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SetAcceptSuccessResponseData) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetAcceptSuccessResponseData) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SetAcceptSuccessResponseData) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SetAcceptSuccessResponseData) SetStatus(v string) {
	o.Status = &v
}

// GetOctoPayUrl returns the OctoPayUrl field value if set, zero value otherwise.
func (o *SetAcceptSuccessResponseData) GetOctoPayUrl() string {
	if o == nil || IsNil(o.OctoPayUrl) {
		var ret string
		return ret
	}
	return *o.OctoPayUrl
}

// GetOctoPayUrlOk returns a tuple with the OctoPayUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetAcceptSuccessResponseData) GetOctoPayUrlOk() (*string, bool) {
	if o == nil || IsNil(o.OctoPayUrl) {
		return nil, false
	}
	return o.OctoPayUrl, true
}

// HasOctoPayUrl returns a boolean if a field has been set.
func (o *SetAcceptSuccessResponseData) HasOctoPayUrl() bool {
	if o != nil && !IsNil(o.OctoPayUrl) {
		return true
	}

	return false
}

// SetOctoPayUrl gets a reference to the given string and assigns it to the OctoPayUrl field.
func (o *SetAcceptSuccessResponseData) SetOctoPayUrl(v string) {
	o.OctoPayUrl = &v
}

// GetTransferSum returns the TransferSum field value if set, zero value otherwise.
func (o *SetAcceptSuccessResponseData) GetTransferSum() float64 {
	if o == nil || IsNil(o.TransferSum) {
		var ret float64
		return ret
	}
	return *o.TransferSum
}

// GetTransferSumOk returns a tuple with the TransferSum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetAcceptSuccessResponseData) GetTransferSumOk() (*float64, bool) {
	if o == nil || IsNil(o.TransferSum) {
		return nil, false
	}
	return o.TransferSum, true
}

// HasTransferSum returns a boolean if a field has been set.
func (o *SetAcceptSuccessResponseData) HasTransferSum() bool {
	if o != nil && !IsNil(o.TransferSum) {
		return true
	}

	return false
}

// SetTransferSum gets a reference to the given float64 and assigns it to the TransferSum field.
func (o *SetAcceptSuccessResponseData) SetTransferSum(v float64) {
	o.TransferSum = &v
}

// GetRefundedSum returns the RefundedSum field value if set, zero value otherwise.
func (o *SetAcceptSuccessResponseData) GetRefundedSum() float64 {
	if o == nil || IsNil(o.RefundedSum) {
		var ret float64
		return ret
	}
	return *o.RefundedSum
}

// GetRefundedSumOk returns a tuple with the RefundedSum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetAcceptSuccessResponseData) GetRefundedSumOk() (*float64, bool) {
	if o == nil || IsNil(o.RefundedSum) {
		return nil, false
	}
	return o.RefundedSum, true
}

// HasRefundedSum returns a boolean if a field has been set.
func (o *SetAcceptSuccessResponseData) HasRefundedSum() bool {
	if o != nil && !IsNil(o.RefundedSum) {
		return true
	}

	return false
}

// SetRefundedSum gets a reference to the given float64 and assigns it to the RefundedSum field.
func (o *SetAcceptSuccessResponseData) SetRefundedSum(v float64) {
	o.RefundedSum = &v
}

// GetTotalSum returns the TotalSum field value if set, zero value otherwise.
func (o *SetAcceptSuccessResponseData) GetTotalSum() float64 {
	if o == nil || IsNil(o.TotalSum) {
		var ret float64
		return ret
	}
	return *o.TotalSum
}

// GetTotalSumOk returns a tuple with the TotalSum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetAcceptSuccessResponseData) GetTotalSumOk() (*float64, bool) {
	if o == nil || IsNil(o.TotalSum) {
		return nil, false
	}
	return o.TotalSum, true
}

// HasTotalSum returns a boolean if a field has been set.
func (o *SetAcceptSuccessResponseData) HasTotalSum() bool {
	if o != nil && !IsNil(o.TotalSum) {
		return true
	}

	return false
}

// SetTotalSum gets a reference to the given float64 and assigns it to the TotalSum field.
func (o *SetAcceptSuccessResponseData) SetTotalSum(v float64) {
	o.TotalSum = &v
}

// GetPayedTime returns the PayedTime field value if set, zero value otherwise.
func (o *SetAcceptSuccessResponseData) GetPayedTime() string {
	if o == nil || IsNil(o.PayedTime) {
		var ret string
		return ret
	}
	return *o.PayedTime
}

// GetPayedTimeOk returns a tuple with the PayedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetAcceptSuccessResponseData) GetPayedTimeOk() (*string, bool) {
	if o == nil || IsNil(o.PayedTime) {
		return nil, false
	}
	return o.PayedTime, true
}

// HasPayedTime returns a boolean if a field has been set.
func (o *SetAcceptSuccessResponseData) HasPayedTime() bool {
	if o != nil && !IsNil(o.PayedTime) {
		return true
	}

	return false
}

// SetPayedTime gets a reference to the given string and assigns it to the PayedTime field.
func (o *SetAcceptSuccessResponseData) SetPayedTime(v string) {
	o.PayedTime = &v
}

func (o SetAcceptSuccessResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetAcceptSuccessResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ShopTransactionId) {
		toSerialize["shop_transaction_id"] = o.ShopTransactionId
	}
	if !IsNil(o.OctoPaymentUUID) {
		toSerialize["octo_payment_UUID"] = o.OctoPaymentUUID
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.OctoPayUrl) {
		toSerialize["octo_pay_url"] = o.OctoPayUrl
	}
	if !IsNil(o.TransferSum) {
		toSerialize["transfer_sum"] = o.TransferSum
	}
	if !IsNil(o.RefundedSum) {
		toSerialize["refunded_sum"] = o.RefundedSum
	}
	if !IsNil(o.TotalSum) {
		toSerialize["total_sum"] = o.TotalSum
	}
	if !IsNil(o.PayedTime) {
		toSerialize["payed_time"] = o.PayedTime
	}
	return toSerialize, nil
}

type NullableSetAcceptSuccessResponseData struct {
	value *SetAcceptSuccessResponseData
	isSet bool
}

func (v NullableSetAcceptSuccessResponseData) Get() *SetAcceptSuccessResponseData {
	return v.value
}

func (v *NullableSetAcceptSuccessResponseData) Set(val *SetAcceptSuccessResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableSetAcceptSuccessResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableSetAcceptSuccessResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetAcceptSuccessResponseData(val *SetAcceptSuccessResponseData) *NullableSetAcceptSuccessResponseData {
	return &NullableSetAcceptSuccessResponseData{value: val, isSet: true}
}

func (v NullableSetAcceptSuccessResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetAcceptSuccessResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
