/*
Octo Payment API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package octoapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RefundRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefundRequest{}

// RefundRequest struct for RefundRequest
type RefundRequest struct {
	OctoShopId      int32   `form:"octo_shop_id" json:"octo_shop_id"`
	ShopRefundId    string  `form:"shop_refund_id" json:"shop_refund_id"`
	OctoSecret      string  `form:"octo_secret" json:"octo_secret"`
	OctoPaymentUUID string  `form:"octo_payment_UUID" json:"octo_payment_UUID"`
	Amount          float64 `form:"amount" json:"amount"`
}

type _RefundRequest RefundRequest

// NewRefundRequest instantiates a new RefundRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefundRequest(octoShopId int32, shopRefundId string, octoSecret string, octoPaymentUUID string, amount float64) *RefundRequest {
	this := RefundRequest{}
	this.OctoShopId = octoShopId
	this.ShopRefundId = shopRefundId
	this.OctoSecret = octoSecret
	this.OctoPaymentUUID = octoPaymentUUID
	this.Amount = amount
	return &this
}

// NewRefundRequestWithDefaults instantiates a new RefundRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefundRequestWithDefaults() *RefundRequest {
	this := RefundRequest{}
	return &this
}

// GetOctoShopId returns the OctoShopId field value
func (o *RefundRequest) GetOctoShopId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OctoShopId
}

// GetOctoShopIdOk returns a tuple with the OctoShopId field value
// and a boolean to check if the value has been set.
func (o *RefundRequest) GetOctoShopIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OctoShopId, true
}

// SetOctoShopId sets field value
func (o *RefundRequest) SetOctoShopId(v int32) {
	o.OctoShopId = v
}

// GetShopRefundId returns the ShopRefundId field value
func (o *RefundRequest) GetShopRefundId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShopRefundId
}

// GetShopRefundIdOk returns a tuple with the ShopRefundId field value
// and a boolean to check if the value has been set.
func (o *RefundRequest) GetShopRefundIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShopRefundId, true
}

// SetShopRefundId sets field value
func (o *RefundRequest) SetShopRefundId(v string) {
	o.ShopRefundId = v
}

// GetOctoSecret returns the OctoSecret field value
func (o *RefundRequest) GetOctoSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OctoSecret
}

// GetOctoSecretOk returns a tuple with the OctoSecret field value
// and a boolean to check if the value has been set.
func (o *RefundRequest) GetOctoSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OctoSecret, true
}

// SetOctoSecret sets field value
func (o *RefundRequest) SetOctoSecret(v string) {
	o.OctoSecret = v
}

// GetOctoPaymentUUID returns the OctoPaymentUUID field value
func (o *RefundRequest) GetOctoPaymentUUID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OctoPaymentUUID
}

// GetOctoPaymentUUIDOk returns a tuple with the OctoPaymentUUID field value
// and a boolean to check if the value has been set.
func (o *RefundRequest) GetOctoPaymentUUIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OctoPaymentUUID, true
}

// SetOctoPaymentUUID sets field value
func (o *RefundRequest) SetOctoPaymentUUID(v string) {
	o.OctoPaymentUUID = v
}

// GetAmount returns the Amount field value
func (o *RefundRequest) GetAmount() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *RefundRequest) GetAmountOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *RefundRequest) SetAmount(v float64) {
	o.Amount = v
}

func (o RefundRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefundRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["octo_shop_id"] = o.OctoShopId
	toSerialize["shop_refund_id"] = o.ShopRefundId
	toSerialize["octo_secret"] = o.OctoSecret
	toSerialize["octo_payment_UUID"] = o.OctoPaymentUUID
	toSerialize["amount"] = o.Amount
	return toSerialize, nil
}

func (o *RefundRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"octo_shop_id",
		"shop_refund_id",
		"octo_secret",
		"octo_payment_UUID",
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRefundRequest := _RefundRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRefundRequest)

	if err != nil {
		return err
	}

	*o = RefundRequest(varRefundRequest)

	return err
}

type NullableRefundRequest struct {
	value *RefundRequest
	isSet bool
}

func (v NullableRefundRequest) Get() *RefundRequest {
	return v.value
}

func (v *NullableRefundRequest) Set(val *RefundRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRefundRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRefundRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefundRequest(val *RefundRequest) *NullableRefundRequest {
	return &NullableRefundRequest{value: val, isSet: true}
}

func (v NullableRefundRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefundRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
