/*
Octo Payment API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package octoapi

import (
	"encoding/json"
)

// checks if the SetAcceptSuccessResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetAcceptSuccessResponse{}

// SetAcceptSuccessResponse struct for SetAcceptSuccessResponse
type SetAcceptSuccessResponse struct {
	Error                   *int32                        `form:"error" json:"error,omitempty"`
	Data                    *SetAcceptSuccessResponseData `form:"data" json:"data,omitempty"`
	ApiMessageForDevelopers *string                       `form:"apiMessageForDevelopers" json:"apiMessageForDevelopers,omitempty"`
}

// NewSetAcceptSuccessResponse instantiates a new SetAcceptSuccessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetAcceptSuccessResponse() *SetAcceptSuccessResponse {
	this := SetAcceptSuccessResponse{}
	return &this
}

// NewSetAcceptSuccessResponseWithDefaults instantiates a new SetAcceptSuccessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetAcceptSuccessResponseWithDefaults() *SetAcceptSuccessResponse {
	this := SetAcceptSuccessResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *SetAcceptSuccessResponse) GetError() int32 {
	if o == nil || IsNil(o.Error) {
		var ret int32
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetAcceptSuccessResponse) GetErrorOk() (*int32, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *SetAcceptSuccessResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given int32 and assigns it to the Error field.
func (o *SetAcceptSuccessResponse) SetError(v int32) {
	o.Error = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SetAcceptSuccessResponse) GetData() SetAcceptSuccessResponseData {
	if o == nil || IsNil(o.Data) {
		var ret SetAcceptSuccessResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetAcceptSuccessResponse) GetDataOk() (*SetAcceptSuccessResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SetAcceptSuccessResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given SetAcceptSuccessResponseData and assigns it to the Data field.
func (o *SetAcceptSuccessResponse) SetData(v SetAcceptSuccessResponseData) {
	o.Data = &v
}

// GetApiMessageForDevelopers returns the ApiMessageForDevelopers field value if set, zero value otherwise.
func (o *SetAcceptSuccessResponse) GetApiMessageForDevelopers() string {
	if o == nil || IsNil(o.ApiMessageForDevelopers) {
		var ret string
		return ret
	}
	return *o.ApiMessageForDevelopers
}

// GetApiMessageForDevelopersOk returns a tuple with the ApiMessageForDevelopers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetAcceptSuccessResponse) GetApiMessageForDevelopersOk() (*string, bool) {
	if o == nil || IsNil(o.ApiMessageForDevelopers) {
		return nil, false
	}
	return o.ApiMessageForDevelopers, true
}

// HasApiMessageForDevelopers returns a boolean if a field has been set.
func (o *SetAcceptSuccessResponse) HasApiMessageForDevelopers() bool {
	if o != nil && !IsNil(o.ApiMessageForDevelopers) {
		return true
	}

	return false
}

// SetApiMessageForDevelopers gets a reference to the given string and assigns it to the ApiMessageForDevelopers field.
func (o *SetAcceptSuccessResponse) SetApiMessageForDevelopers(v string) {
	o.ApiMessageForDevelopers = &v
}

func (o SetAcceptSuccessResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetAcceptSuccessResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.ApiMessageForDevelopers) {
		toSerialize["apiMessageForDevelopers"] = o.ApiMessageForDevelopers
	}
	return toSerialize, nil
}

type NullableSetAcceptSuccessResponse struct {
	value *SetAcceptSuccessResponse
	isSet bool
}

func (v NullableSetAcceptSuccessResponse) Get() *SetAcceptSuccessResponse {
	return v.value
}

func (v *NullableSetAcceptSuccessResponse) Set(val *SetAcceptSuccessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSetAcceptSuccessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSetAcceptSuccessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetAcceptSuccessResponse(val *SetAcceptSuccessResponse) *NullableSetAcceptSuccessResponse {
	return &NullableSetAcceptSuccessResponse{value: val, isSet: true}
}

func (v NullableSetAcceptSuccessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetAcceptSuccessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
