/*
Octo Payment API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package octoapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SetAcceptRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetAcceptRequest{}

// SetAcceptRequest struct for SetAcceptRequest
type SetAcceptRequest struct {
	OctoShopId      int32   `form:"octo_shop_id" json:"octo_shop_id"`
	OctoSecret      string  `form:"octo_secret" json:"octo_secret"`
	OctoPaymentUUID string  `form:"octo_payment_UUID" json:"octo_payment_UUID"`
	AcceptStatus    string  `form:"accept_status" json:"accept_status"`
	FinalAmount     float64 `form:"final_amount" json:"final_amount"`
}

type _SetAcceptRequest SetAcceptRequest

// NewSetAcceptRequest instantiates a new SetAcceptRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetAcceptRequest(octoShopId int32, octoSecret string, octoPaymentUUID string, acceptStatus string, finalAmount float64) *SetAcceptRequest {
	this := SetAcceptRequest{}
	this.OctoShopId = octoShopId
	this.OctoSecret = octoSecret
	this.OctoPaymentUUID = octoPaymentUUID
	this.AcceptStatus = acceptStatus
	this.FinalAmount = finalAmount
	return &this
}

// NewSetAcceptRequestWithDefaults instantiates a new SetAcceptRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetAcceptRequestWithDefaults() *SetAcceptRequest {
	this := SetAcceptRequest{}
	return &this
}

// GetOctoShopId returns the OctoShopId field value
func (o *SetAcceptRequest) GetOctoShopId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OctoShopId
}

// GetOctoShopIdOk returns a tuple with the OctoShopId field value
// and a boolean to check if the value has been set.
func (o *SetAcceptRequest) GetOctoShopIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OctoShopId, true
}

// SetOctoShopId sets field value
func (o *SetAcceptRequest) SetOctoShopId(v int32) {
	o.OctoShopId = v
}

// GetOctoSecret returns the OctoSecret field value
func (o *SetAcceptRequest) GetOctoSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OctoSecret
}

// GetOctoSecretOk returns a tuple with the OctoSecret field value
// and a boolean to check if the value has been set.
func (o *SetAcceptRequest) GetOctoSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OctoSecret, true
}

// SetOctoSecret sets field value
func (o *SetAcceptRequest) SetOctoSecret(v string) {
	o.OctoSecret = v
}

// GetOctoPaymentUUID returns the OctoPaymentUUID field value
func (o *SetAcceptRequest) GetOctoPaymentUUID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OctoPaymentUUID
}

// GetOctoPaymentUUIDOk returns a tuple with the OctoPaymentUUID field value
// and a boolean to check if the value has been set.
func (o *SetAcceptRequest) GetOctoPaymentUUIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OctoPaymentUUID, true
}

// SetOctoPaymentUUID sets field value
func (o *SetAcceptRequest) SetOctoPaymentUUID(v string) {
	o.OctoPaymentUUID = v
}

// GetAcceptStatus returns the AcceptStatus field value
func (o *SetAcceptRequest) GetAcceptStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AcceptStatus
}

// GetAcceptStatusOk returns a tuple with the AcceptStatus field value
// and a boolean to check if the value has been set.
func (o *SetAcceptRequest) GetAcceptStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AcceptStatus, true
}

// SetAcceptStatus sets field value
func (o *SetAcceptRequest) SetAcceptStatus(v string) {
	o.AcceptStatus = v
}

// GetFinalAmount returns the FinalAmount field value
func (o *SetAcceptRequest) GetFinalAmount() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.FinalAmount
}

// GetFinalAmountOk returns a tuple with the FinalAmount field value
// and a boolean to check if the value has been set.
func (o *SetAcceptRequest) GetFinalAmountOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FinalAmount, true
}

// SetFinalAmount sets field value
func (o *SetAcceptRequest) SetFinalAmount(v float64) {
	o.FinalAmount = v
}

func (o SetAcceptRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetAcceptRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["octo_shop_id"] = o.OctoShopId
	toSerialize["octo_secret"] = o.OctoSecret
	toSerialize["octo_payment_UUID"] = o.OctoPaymentUUID
	toSerialize["accept_status"] = o.AcceptStatus
	toSerialize["final_amount"] = o.FinalAmount
	return toSerialize, nil
}

func (o *SetAcceptRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"octo_shop_id",
		"octo_secret",
		"octo_payment_UUID",
		"accept_status",
		"final_amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetAcceptRequest := _SetAcceptRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetAcceptRequest)

	if err != nil {
		return err
	}

	*o = SetAcceptRequest(varSetAcceptRequest)

	return err
}

type NullableSetAcceptRequest struct {
	value *SetAcceptRequest
	isSet bool
}

func (v NullableSetAcceptRequest) Get() *SetAcceptRequest {
	return v.value
}

func (v *NullableSetAcceptRequest) Set(val *SetAcceptRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetAcceptRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetAcceptRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetAcceptRequest(val *SetAcceptRequest) *NullableSetAcceptRequest {
	return &NullableSetAcceptRequest{value: val, isSet: true}
}

func (v NullableSetAcceptRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetAcceptRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
