/*
Octo Payment API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package octoapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NotificationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificationRequest{}

// NotificationRequest struct for NotificationRequest
type NotificationRequest struct {
	// Transaction ID on merchant's side
	ShopTransactionId string `form:"shop_transaction_id" json:"shop_transaction_id"` // Transaction ID on merchant&#39;s side
	// Octo payment UUID
	OctoPaymentUUID string `form:"octo_payment_UUID" json:"octo_payment_UUID"` // Octo payment UUID
	// Current transaction status
	Status string `form:"status" json:"status"` // Current transaction status
	// Cryptographic signature
	Signature string `form:"signature" json:"signature"` // Cryptographic signature
	// Hash key for validation
	HashKey string `form:"hash_key" json:"hash_key"` // Hash key for validation
	// Total amount of the payment
	TotalSum *float64 `form:"total_sum" json:"total_sum,omitempty"` // Total amount of the payment
	// Amount transferred after commissions
	TransferSum *float64 `form:"transfer_sum" json:"transfer_sum,omitempty"` // Amount transferred after commissions
	// Refunded amount if any
	RefundedSum *float64 `form:"refunded_sum" json:"refunded_sum,omitempty"` // Refunded amount if any
	// Country where the card was issued
	CardCountry *string `form:"card_country" json:"card_country,omitempty"` // Country where the card was issued
	// Masked card number
	MaskedPan *string `form:"maskedPan" json:"maskedPan,omitempty"` // Masked card number
	// Retrieval Reference Number
	Rrn *string `form:"rrn" json:"rrn,omitempty"` // Retrieval Reference Number
	// Risk level of the transaction
	RiskLevel *int32 `form:"riskLevel" json:"riskLevel,omitempty"` // Risk level of the transaction
	// Timestamp of successful payment
	PayedTime *string `form:"payed_time" json:"payed_time,omitempty"` // Timestamp of successful payment
	// Type of the card used
	CardType *string `form:"card_type" json:"card_type,omitempty"` // Type of the card used
	// Whether the card is physical
	IsPhysicalCard *bool `form:"is_physical_card" json:"is_physical_card,omitempty"` // Whether the card is physical
	// Currency code of the payment (e.g., 'UZS', USD', 'EUR', 'RUB')
	Currency *string `form:"currency" json:"currency,omitempty"` // Currency code of the payment (e.g., &#39;UZS&#39;, USD&#39;, &#39;EUR&#39;, &#39;RUB&#39;)
}

type _NotificationRequest NotificationRequest

// NewNotificationRequest instantiates a new NotificationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationRequest(shopTransactionId string, octoPaymentUUID string, status string, signature string, hashKey string) *NotificationRequest {
	this := NotificationRequest{}
	this.ShopTransactionId = shopTransactionId
	this.OctoPaymentUUID = octoPaymentUUID
	this.Status = status
	this.Signature = signature
	this.HashKey = hashKey
	return &this
}

// NewNotificationRequestWithDefaults instantiates a new NotificationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationRequestWithDefaults() *NotificationRequest {
	this := NotificationRequest{}
	return &this
}

// GetShopTransactionId returns the ShopTransactionId field value
func (o *NotificationRequest) GetShopTransactionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShopTransactionId
}

// GetShopTransactionIdOk returns a tuple with the ShopTransactionId field value
// and a boolean to check if the value has been set.
func (o *NotificationRequest) GetShopTransactionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShopTransactionId, true
}

// SetShopTransactionId sets field value
func (o *NotificationRequest) SetShopTransactionId(v string) {
	o.ShopTransactionId = v
}

// GetOctoPaymentUUID returns the OctoPaymentUUID field value
func (o *NotificationRequest) GetOctoPaymentUUID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OctoPaymentUUID
}

// GetOctoPaymentUUIDOk returns a tuple with the OctoPaymentUUID field value
// and a boolean to check if the value has been set.
func (o *NotificationRequest) GetOctoPaymentUUIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OctoPaymentUUID, true
}

// SetOctoPaymentUUID sets field value
func (o *NotificationRequest) SetOctoPaymentUUID(v string) {
	o.OctoPaymentUUID = v
}

// GetStatus returns the Status field value
func (o *NotificationRequest) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *NotificationRequest) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *NotificationRequest) SetStatus(v string) {
	o.Status = v
}

// GetSignature returns the Signature field value
func (o *NotificationRequest) GetSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value
// and a boolean to check if the value has been set.
func (o *NotificationRequest) GetSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signature, true
}

// SetSignature sets field value
func (o *NotificationRequest) SetSignature(v string) {
	o.Signature = v
}

// GetHashKey returns the HashKey field value
func (o *NotificationRequest) GetHashKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HashKey
}

// GetHashKeyOk returns a tuple with the HashKey field value
// and a boolean to check if the value has been set.
func (o *NotificationRequest) GetHashKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HashKey, true
}

// SetHashKey sets field value
func (o *NotificationRequest) SetHashKey(v string) {
	o.HashKey = v
}

// GetTotalSum returns the TotalSum field value if set, zero value otherwise.
func (o *NotificationRequest) GetTotalSum() float64 {
	if o == nil || IsNil(o.TotalSum) {
		var ret float64
		return ret
	}
	return *o.TotalSum
}

// GetTotalSumOk returns a tuple with the TotalSum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRequest) GetTotalSumOk() (*float64, bool) {
	if o == nil || IsNil(o.TotalSum) {
		return nil, false
	}
	return o.TotalSum, true
}

// HasTotalSum returns a boolean if a field has been set.
func (o *NotificationRequest) HasTotalSum() bool {
	if o != nil && !IsNil(o.TotalSum) {
		return true
	}

	return false
}

// SetTotalSum gets a reference to the given float64 and assigns it to the TotalSum field.
func (o *NotificationRequest) SetTotalSum(v float64) {
	o.TotalSum = &v
}

// GetTransferSum returns the TransferSum field value if set, zero value otherwise.
func (o *NotificationRequest) GetTransferSum() float64 {
	if o == nil || IsNil(o.TransferSum) {
		var ret float64
		return ret
	}
	return *o.TransferSum
}

// GetTransferSumOk returns a tuple with the TransferSum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRequest) GetTransferSumOk() (*float64, bool) {
	if o == nil || IsNil(o.TransferSum) {
		return nil, false
	}
	return o.TransferSum, true
}

// HasTransferSum returns a boolean if a field has been set.
func (o *NotificationRequest) HasTransferSum() bool {
	if o != nil && !IsNil(o.TransferSum) {
		return true
	}

	return false
}

// SetTransferSum gets a reference to the given float64 and assigns it to the TransferSum field.
func (o *NotificationRequest) SetTransferSum(v float64) {
	o.TransferSum = &v
}

// GetRefundedSum returns the RefundedSum field value if set, zero value otherwise.
func (o *NotificationRequest) GetRefundedSum() float64 {
	if o == nil || IsNil(o.RefundedSum) {
		var ret float64
		return ret
	}
	return *o.RefundedSum
}

// GetRefundedSumOk returns a tuple with the RefundedSum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRequest) GetRefundedSumOk() (*float64, bool) {
	if o == nil || IsNil(o.RefundedSum) {
		return nil, false
	}
	return o.RefundedSum, true
}

// HasRefundedSum returns a boolean if a field has been set.
func (o *NotificationRequest) HasRefundedSum() bool {
	if o != nil && !IsNil(o.RefundedSum) {
		return true
	}

	return false
}

// SetRefundedSum gets a reference to the given float64 and assigns it to the RefundedSum field.
func (o *NotificationRequest) SetRefundedSum(v float64) {
	o.RefundedSum = &v
}

// GetCardCountry returns the CardCountry field value if set, zero value otherwise.
func (o *NotificationRequest) GetCardCountry() string {
	if o == nil || IsNil(o.CardCountry) {
		var ret string
		return ret
	}
	return *o.CardCountry
}

// GetCardCountryOk returns a tuple with the CardCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRequest) GetCardCountryOk() (*string, bool) {
	if o == nil || IsNil(o.CardCountry) {
		return nil, false
	}
	return o.CardCountry, true
}

// HasCardCountry returns a boolean if a field has been set.
func (o *NotificationRequest) HasCardCountry() bool {
	if o != nil && !IsNil(o.CardCountry) {
		return true
	}

	return false
}

// SetCardCountry gets a reference to the given string and assigns it to the CardCountry field.
func (o *NotificationRequest) SetCardCountry(v string) {
	o.CardCountry = &v
}

// GetMaskedPan returns the MaskedPan field value if set, zero value otherwise.
func (o *NotificationRequest) GetMaskedPan() string {
	if o == nil || IsNil(o.MaskedPan) {
		var ret string
		return ret
	}
	return *o.MaskedPan
}

// GetMaskedPanOk returns a tuple with the MaskedPan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRequest) GetMaskedPanOk() (*string, bool) {
	if o == nil || IsNil(o.MaskedPan) {
		return nil, false
	}
	return o.MaskedPan, true
}

// HasMaskedPan returns a boolean if a field has been set.
func (o *NotificationRequest) HasMaskedPan() bool {
	if o != nil && !IsNil(o.MaskedPan) {
		return true
	}

	return false
}

// SetMaskedPan gets a reference to the given string and assigns it to the MaskedPan field.
func (o *NotificationRequest) SetMaskedPan(v string) {
	o.MaskedPan = &v
}

// GetRrn returns the Rrn field value if set, zero value otherwise.
func (o *NotificationRequest) GetRrn() string {
	if o == nil || IsNil(o.Rrn) {
		var ret string
		return ret
	}
	return *o.Rrn
}

// GetRrnOk returns a tuple with the Rrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRequest) GetRrnOk() (*string, bool) {
	if o == nil || IsNil(o.Rrn) {
		return nil, false
	}
	return o.Rrn, true
}

// HasRrn returns a boolean if a field has been set.
func (o *NotificationRequest) HasRrn() bool {
	if o != nil && !IsNil(o.Rrn) {
		return true
	}

	return false
}

// SetRrn gets a reference to the given string and assigns it to the Rrn field.
func (o *NotificationRequest) SetRrn(v string) {
	o.Rrn = &v
}

// GetRiskLevel returns the RiskLevel field value if set, zero value otherwise.
func (o *NotificationRequest) GetRiskLevel() int32 {
	if o == nil || IsNil(o.RiskLevel) {
		var ret int32
		return ret
	}
	return *o.RiskLevel
}

// GetRiskLevelOk returns a tuple with the RiskLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRequest) GetRiskLevelOk() (*int32, bool) {
	if o == nil || IsNil(o.RiskLevel) {
		return nil, false
	}
	return o.RiskLevel, true
}

// HasRiskLevel returns a boolean if a field has been set.
func (o *NotificationRequest) HasRiskLevel() bool {
	if o != nil && !IsNil(o.RiskLevel) {
		return true
	}

	return false
}

// SetRiskLevel gets a reference to the given int32 and assigns it to the RiskLevel field.
func (o *NotificationRequest) SetRiskLevel(v int32) {
	o.RiskLevel = &v
}

// GetPayedTime returns the PayedTime field value if set, zero value otherwise.
func (o *NotificationRequest) GetPayedTime() string {
	if o == nil || IsNil(o.PayedTime) {
		var ret string
		return ret
	}
	return *o.PayedTime
}

// GetPayedTimeOk returns a tuple with the PayedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRequest) GetPayedTimeOk() (*string, bool) {
	if o == nil || IsNil(o.PayedTime) {
		return nil, false
	}
	return o.PayedTime, true
}

// HasPayedTime returns a boolean if a field has been set.
func (o *NotificationRequest) HasPayedTime() bool {
	if o != nil && !IsNil(o.PayedTime) {
		return true
	}

	return false
}

// SetPayedTime gets a reference to the given string and assigns it to the PayedTime field.
func (o *NotificationRequest) SetPayedTime(v string) {
	o.PayedTime = &v
}

// GetCardType returns the CardType field value if set, zero value otherwise.
func (o *NotificationRequest) GetCardType() string {
	if o == nil || IsNil(o.CardType) {
		var ret string
		return ret
	}
	return *o.CardType
}

// GetCardTypeOk returns a tuple with the CardType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRequest) GetCardTypeOk() (*string, bool) {
	if o == nil || IsNil(o.CardType) {
		return nil, false
	}
	return o.CardType, true
}

// HasCardType returns a boolean if a field has been set.
func (o *NotificationRequest) HasCardType() bool {
	if o != nil && !IsNil(o.CardType) {
		return true
	}

	return false
}

// SetCardType gets a reference to the given string and assigns it to the CardType field.
func (o *NotificationRequest) SetCardType(v string) {
	o.CardType = &v
}

// GetIsPhysicalCard returns the IsPhysicalCard field value if set, zero value otherwise.
func (o *NotificationRequest) GetIsPhysicalCard() bool {
	if o == nil || IsNil(o.IsPhysicalCard) {
		var ret bool
		return ret
	}
	return *o.IsPhysicalCard
}

// GetIsPhysicalCardOk returns a tuple with the IsPhysicalCard field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRequest) GetIsPhysicalCardOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPhysicalCard) {
		return nil, false
	}
	return o.IsPhysicalCard, true
}

// HasIsPhysicalCard returns a boolean if a field has been set.
func (o *NotificationRequest) HasIsPhysicalCard() bool {
	if o != nil && !IsNil(o.IsPhysicalCard) {
		return true
	}

	return false
}

// SetIsPhysicalCard gets a reference to the given bool and assigns it to the IsPhysicalCard field.
func (o *NotificationRequest) SetIsPhysicalCard(v bool) {
	o.IsPhysicalCard = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *NotificationRequest) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRequest) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *NotificationRequest) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *NotificationRequest) SetCurrency(v string) {
	o.Currency = &v
}

func (o NotificationRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["shop_transaction_id"] = o.ShopTransactionId
	toSerialize["octo_payment_UUID"] = o.OctoPaymentUUID
	toSerialize["status"] = o.Status
	toSerialize["signature"] = o.Signature
	toSerialize["hash_key"] = o.HashKey
	if !IsNil(o.TotalSum) {
		toSerialize["total_sum"] = o.TotalSum
	}
	if !IsNil(o.TransferSum) {
		toSerialize["transfer_sum"] = o.TransferSum
	}
	if !IsNil(o.RefundedSum) {
		toSerialize["refunded_sum"] = o.RefundedSum
	}
	if !IsNil(o.CardCountry) {
		toSerialize["card_country"] = o.CardCountry
	}
	if !IsNil(o.MaskedPan) {
		toSerialize["maskedPan"] = o.MaskedPan
	}
	if !IsNil(o.Rrn) {
		toSerialize["rrn"] = o.Rrn
	}
	if !IsNil(o.RiskLevel) {
		toSerialize["riskLevel"] = o.RiskLevel
	}
	if !IsNil(o.PayedTime) {
		toSerialize["payed_time"] = o.PayedTime
	}
	if !IsNil(o.CardType) {
		toSerialize["card_type"] = o.CardType
	}
	if !IsNil(o.IsPhysicalCard) {
		toSerialize["is_physical_card"] = o.IsPhysicalCard
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	return toSerialize, nil
}

func (o *NotificationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"shop_transaction_id",
		"octo_payment_UUID",
		"status",
		"signature",
		"hash_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNotificationRequest := _NotificationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNotificationRequest)

	if err != nil {
		return err
	}

	*o = NotificationRequest(varNotificationRequest)

	return err
}

type NullableNotificationRequest struct {
	value *NotificationRequest
	isSet bool
}

func (v NullableNotificationRequest) Get() *NotificationRequest {
	return v.value
}

func (v *NullableNotificationRequest) Set(val *NotificationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationRequest(val *NotificationRequest) *NullableNotificationRequest {
	return &NullableNotificationRequest{value: val, isSet: true}
}

func (v NullableNotificationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
