/*
Octo Payment API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package octoapi

import (
	"encoding/json"
)

// checks if the PreparePaymentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PreparePaymentResponse{}

// PreparePaymentResponse struct for PreparePaymentResponse
type PreparePaymentResponse struct {
	Error                   *int32                             `form:"error" json:"error,omitempty"`
	ErrMessage              *string                            `form:"errMessage" json:"errMessage,omitempty"`
	ErrorMessage            *string                            `form:"errorMessage" json:"errorMessage,omitempty"`
	ApiMessageForDevelopers *string                            `form:"apiMessageForDevelopers" json:"apiMessageForDevelopers,omitempty"`
	ShopTransactionId       *string                            `form:"shop_transaction_id" json:"shop_transaction_id,omitempty"`
	OctoPaymentUUID         *string                            `form:"octo_payment_UUID" json:"octo_payment_UUID,omitempty"`
	Status                  *string                            `form:"status" json:"status,omitempty"`
	OctoPayUrl              *string                            `form:"octo_pay_url" json:"octo_pay_url,omitempty"`
	RefundedSum             *float32                           `form:"refunded_sum" json:"refunded_sum,omitempty"`
	TotalSum                *float32                           `form:"total_sum" json:"total_sum,omitempty"`
	Data                    *PreparePaymentSuccessResponseData `form:"data" json:"data,omitempty"`
}

// NewPreparePaymentResponse instantiates a new PreparePaymentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPreparePaymentResponse() *PreparePaymentResponse {
	this := PreparePaymentResponse{}
	return &this
}

// NewPreparePaymentResponseWithDefaults instantiates a new PreparePaymentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPreparePaymentResponseWithDefaults() *PreparePaymentResponse {
	this := PreparePaymentResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *PreparePaymentResponse) GetError() int32 {
	if o == nil || IsNil(o.Error) {
		var ret int32
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentResponse) GetErrorOk() (*int32, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *PreparePaymentResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given int32 and assigns it to the Error field.
func (o *PreparePaymentResponse) SetError(v int32) {
	o.Error = &v
}

// GetErrMessage returns the ErrMessage field value if set, zero value otherwise.
func (o *PreparePaymentResponse) GetErrMessage() string {
	if o == nil || IsNil(o.ErrMessage) {
		var ret string
		return ret
	}
	return *o.ErrMessage
}

// GetErrMessageOk returns a tuple with the ErrMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentResponse) GetErrMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrMessage) {
		return nil, false
	}
	return o.ErrMessage, true
}

// HasErrMessage returns a boolean if a field has been set.
func (o *PreparePaymentResponse) HasErrMessage() bool {
	if o != nil && !IsNil(o.ErrMessage) {
		return true
	}

	return false
}

// SetErrMessage gets a reference to the given string and assigns it to the ErrMessage field.
func (o *PreparePaymentResponse) SetErrMessage(v string) {
	o.ErrMessage = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *PreparePaymentResponse) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentResponse) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *PreparePaymentResponse) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *PreparePaymentResponse) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetApiMessageForDevelopers returns the ApiMessageForDevelopers field value if set, zero value otherwise.
func (o *PreparePaymentResponse) GetApiMessageForDevelopers() string {
	if o == nil || IsNil(o.ApiMessageForDevelopers) {
		var ret string
		return ret
	}
	return *o.ApiMessageForDevelopers
}

// GetApiMessageForDevelopersOk returns a tuple with the ApiMessageForDevelopers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentResponse) GetApiMessageForDevelopersOk() (*string, bool) {
	if o == nil || IsNil(o.ApiMessageForDevelopers) {
		return nil, false
	}
	return o.ApiMessageForDevelopers, true
}

// HasApiMessageForDevelopers returns a boolean if a field has been set.
func (o *PreparePaymentResponse) HasApiMessageForDevelopers() bool {
	if o != nil && !IsNil(o.ApiMessageForDevelopers) {
		return true
	}

	return false
}

// SetApiMessageForDevelopers gets a reference to the given string and assigns it to the ApiMessageForDevelopers field.
func (o *PreparePaymentResponse) SetApiMessageForDevelopers(v string) {
	o.ApiMessageForDevelopers = &v
}

// GetShopTransactionId returns the ShopTransactionId field value if set, zero value otherwise.
func (o *PreparePaymentResponse) GetShopTransactionId() string {
	if o == nil || IsNil(o.ShopTransactionId) {
		var ret string
		return ret
	}
	return *o.ShopTransactionId
}

// GetShopTransactionIdOk returns a tuple with the ShopTransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentResponse) GetShopTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.ShopTransactionId) {
		return nil, false
	}
	return o.ShopTransactionId, true
}

// HasShopTransactionId returns a boolean if a field has been set.
func (o *PreparePaymentResponse) HasShopTransactionId() bool {
	if o != nil && !IsNil(o.ShopTransactionId) {
		return true
	}

	return false
}

// SetShopTransactionId gets a reference to the given string and assigns it to the ShopTransactionId field.
func (o *PreparePaymentResponse) SetShopTransactionId(v string) {
	o.ShopTransactionId = &v
}

// GetOctoPaymentUUID returns the OctoPaymentUUID field value if set, zero value otherwise.
func (o *PreparePaymentResponse) GetOctoPaymentUUID() string {
	if o == nil || IsNil(o.OctoPaymentUUID) {
		var ret string
		return ret
	}
	return *o.OctoPaymentUUID
}

// GetOctoPaymentUUIDOk returns a tuple with the OctoPaymentUUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentResponse) GetOctoPaymentUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.OctoPaymentUUID) {
		return nil, false
	}
	return o.OctoPaymentUUID, true
}

// HasOctoPaymentUUID returns a boolean if a field has been set.
func (o *PreparePaymentResponse) HasOctoPaymentUUID() bool {
	if o != nil && !IsNil(o.OctoPaymentUUID) {
		return true
	}

	return false
}

// SetOctoPaymentUUID gets a reference to the given string and assigns it to the OctoPaymentUUID field.
func (o *PreparePaymentResponse) SetOctoPaymentUUID(v string) {
	o.OctoPaymentUUID = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PreparePaymentResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PreparePaymentResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PreparePaymentResponse) SetStatus(v string) {
	o.Status = &v
}

// GetOctoPayUrl returns the OctoPayUrl field value if set, zero value otherwise.
func (o *PreparePaymentResponse) GetOctoPayUrl() string {
	if o == nil || IsNil(o.OctoPayUrl) {
		var ret string
		return ret
	}
	return *o.OctoPayUrl
}

// GetOctoPayUrlOk returns a tuple with the OctoPayUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentResponse) GetOctoPayUrlOk() (*string, bool) {
	if o == nil || IsNil(o.OctoPayUrl) {
		return nil, false
	}
	return o.OctoPayUrl, true
}

// HasOctoPayUrl returns a boolean if a field has been set.
func (o *PreparePaymentResponse) HasOctoPayUrl() bool {
	if o != nil && !IsNil(o.OctoPayUrl) {
		return true
	}

	return false
}

// SetOctoPayUrl gets a reference to the given string and assigns it to the OctoPayUrl field.
func (o *PreparePaymentResponse) SetOctoPayUrl(v string) {
	o.OctoPayUrl = &v
}

// GetRefundedSum returns the RefundedSum field value if set, zero value otherwise.
func (o *PreparePaymentResponse) GetRefundedSum() float32 {
	if o == nil || IsNil(o.RefundedSum) {
		var ret float32
		return ret
	}
	return *o.RefundedSum
}

// GetRefundedSumOk returns a tuple with the RefundedSum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentResponse) GetRefundedSumOk() (*float32, bool) {
	if o == nil || IsNil(o.RefundedSum) {
		return nil, false
	}
	return o.RefundedSum, true
}

// HasRefundedSum returns a boolean if a field has been set.
func (o *PreparePaymentResponse) HasRefundedSum() bool {
	if o != nil && !IsNil(o.RefundedSum) {
		return true
	}

	return false
}

// SetRefundedSum gets a reference to the given float32 and assigns it to the RefundedSum field.
func (o *PreparePaymentResponse) SetRefundedSum(v float32) {
	o.RefundedSum = &v
}

// GetTotalSum returns the TotalSum field value if set, zero value otherwise.
func (o *PreparePaymentResponse) GetTotalSum() float32 {
	if o == nil || IsNil(o.TotalSum) {
		var ret float32
		return ret
	}
	return *o.TotalSum
}

// GetTotalSumOk returns a tuple with the TotalSum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentResponse) GetTotalSumOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalSum) {
		return nil, false
	}
	return o.TotalSum, true
}

// HasTotalSum returns a boolean if a field has been set.
func (o *PreparePaymentResponse) HasTotalSum() bool {
	if o != nil && !IsNil(o.TotalSum) {
		return true
	}

	return false
}

// SetTotalSum gets a reference to the given float32 and assigns it to the TotalSum field.
func (o *PreparePaymentResponse) SetTotalSum(v float32) {
	o.TotalSum = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PreparePaymentResponse) GetData() PreparePaymentSuccessResponseData {
	if o == nil || IsNil(o.Data) {
		var ret PreparePaymentSuccessResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentResponse) GetDataOk() (*PreparePaymentSuccessResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PreparePaymentResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given PreparePaymentSuccessResponseData and assigns it to the Data field.
func (o *PreparePaymentResponse) SetData(v PreparePaymentSuccessResponseData) {
	o.Data = &v
}

func (o PreparePaymentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PreparePaymentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.ErrMessage) {
		toSerialize["errMessage"] = o.ErrMessage
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	if !IsNil(o.ApiMessageForDevelopers) {
		toSerialize["apiMessageForDevelopers"] = o.ApiMessageForDevelopers
	}
	if !IsNil(o.ShopTransactionId) {
		toSerialize["shop_transaction_id"] = o.ShopTransactionId
	}
	if !IsNil(o.OctoPaymentUUID) {
		toSerialize["octo_payment_UUID"] = o.OctoPaymentUUID
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.OctoPayUrl) {
		toSerialize["octo_pay_url"] = o.OctoPayUrl
	}
	if !IsNil(o.RefundedSum) {
		toSerialize["refunded_sum"] = o.RefundedSum
	}
	if !IsNil(o.TotalSum) {
		toSerialize["total_sum"] = o.TotalSum
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullablePreparePaymentResponse struct {
	value *PreparePaymentResponse
	isSet bool
}

func (v NullablePreparePaymentResponse) Get() *PreparePaymentResponse {
	return v.value
}

func (v *NullablePreparePaymentResponse) Set(val *PreparePaymentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePreparePaymentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePreparePaymentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreparePaymentResponse(val *PreparePaymentResponse) *NullablePreparePaymentResponse {
	return &NullablePreparePaymentResponse{value: val, isSet: true}
}

func (v NullablePreparePaymentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreparePaymentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
