/*
Octo Payment API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package octoapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CallbackRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CallbackRequest{}

// CallbackRequest struct for CallbackRequest
type CallbackRequest struct {
	OctoSecret      string   `form:"octo_secret" json:"octo_secret"`
	OctoPaymentUUID string   `form:"octo_payment_UUID" json:"octo_payment_UUID"`
	AcceptStatus    string   `form:"accept_status" json:"accept_status"`
	FinalAmount     *float32 `form:"final_amount" json:"final_amount,omitempty"`
}

type _CallbackRequest CallbackRequest

// NewCallbackRequest instantiates a new CallbackRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCallbackRequest(octoSecret string, octoPaymentUUID string, acceptStatus string) *CallbackRequest {
	this := CallbackRequest{}
	this.OctoSecret = octoSecret
	this.OctoPaymentUUID = octoPaymentUUID
	this.AcceptStatus = acceptStatus
	return &this
}

// NewCallbackRequestWithDefaults instantiates a new CallbackRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCallbackRequestWithDefaults() *CallbackRequest {
	this := CallbackRequest{}
	return &this
}

// GetOctoSecret returns the OctoSecret field value
func (o *CallbackRequest) GetOctoSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OctoSecret
}

// GetOctoSecretOk returns a tuple with the OctoSecret field value
// and a boolean to check if the value has been set.
func (o *CallbackRequest) GetOctoSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OctoSecret, true
}

// SetOctoSecret sets field value
func (o *CallbackRequest) SetOctoSecret(v string) {
	o.OctoSecret = v
}

// GetOctoPaymentUUID returns the OctoPaymentUUID field value
func (o *CallbackRequest) GetOctoPaymentUUID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OctoPaymentUUID
}

// GetOctoPaymentUUIDOk returns a tuple with the OctoPaymentUUID field value
// and a boolean to check if the value has been set.
func (o *CallbackRequest) GetOctoPaymentUUIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OctoPaymentUUID, true
}

// SetOctoPaymentUUID sets field value
func (o *CallbackRequest) SetOctoPaymentUUID(v string) {
	o.OctoPaymentUUID = v
}

// GetAcceptStatus returns the AcceptStatus field value
func (o *CallbackRequest) GetAcceptStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AcceptStatus
}

// GetAcceptStatusOk returns a tuple with the AcceptStatus field value
// and a boolean to check if the value has been set.
func (o *CallbackRequest) GetAcceptStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AcceptStatus, true
}

// SetAcceptStatus sets field value
func (o *CallbackRequest) SetAcceptStatus(v string) {
	o.AcceptStatus = v
}

// GetFinalAmount returns the FinalAmount field value if set, zero value otherwise.
func (o *CallbackRequest) GetFinalAmount() float32 {
	if o == nil || IsNil(o.FinalAmount) {
		var ret float32
		return ret
	}
	return *o.FinalAmount
}

// GetFinalAmountOk returns a tuple with the FinalAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallbackRequest) GetFinalAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.FinalAmount) {
		return nil, false
	}
	return o.FinalAmount, true
}

// HasFinalAmount returns a boolean if a field has been set.
func (o *CallbackRequest) HasFinalAmount() bool {
	if o != nil && !IsNil(o.FinalAmount) {
		return true
	}

	return false
}

// SetFinalAmount gets a reference to the given float32 and assigns it to the FinalAmount field.
func (o *CallbackRequest) SetFinalAmount(v float32) {
	o.FinalAmount = &v
}

func (o CallbackRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CallbackRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["octo_secret"] = o.OctoSecret
	toSerialize["octo_payment_UUID"] = o.OctoPaymentUUID
	toSerialize["accept_status"] = o.AcceptStatus
	if !IsNil(o.FinalAmount) {
		toSerialize["final_amount"] = o.FinalAmount
	}
	return toSerialize, nil
}

func (o *CallbackRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"octo_secret",
		"octo_payment_UUID",
		"accept_status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCallbackRequest := _CallbackRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCallbackRequest)

	if err != nil {
		return err
	}

	*o = CallbackRequest(varCallbackRequest)

	return err
}

type NullableCallbackRequest struct {
	value *CallbackRequest
	isSet bool
}

func (v NullableCallbackRequest) Get() *CallbackRequest {
	return v.value
}

func (v *NullableCallbackRequest) Set(val *CallbackRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCallbackRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCallbackRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCallbackRequest(val *CallbackRequest) *NullableCallbackRequest {
	return &NullableCallbackRequest{value: val, isSet: true}
}

func (v NullableCallbackRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCallbackRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
