/*
Octo Payment API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package octoapi

import (
	"encoding/json"
)

// checks if the CallbackResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CallbackResponse{}

// CallbackResponse struct for CallbackResponse
type CallbackResponse struct {
	AcceptStatus *string  `form:"accept_status" json:"accept_status,omitempty"`
	FinalAmount  *float64 `form:"final_amount" json:"final_amount,omitempty"`
}

// NewCallbackResponse instantiates a new CallbackResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCallbackResponse() *CallbackResponse {
	this := CallbackResponse{}
	return &this
}

// NewCallbackResponseWithDefaults instantiates a new CallbackResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCallbackResponseWithDefaults() *CallbackResponse {
	this := CallbackResponse{}
	return &this
}

// GetAcceptStatus returns the AcceptStatus field value if set, zero value otherwise.
func (o *CallbackResponse) GetAcceptStatus() string {
	if o == nil || IsNil(o.AcceptStatus) {
		var ret string
		return ret
	}
	return *o.AcceptStatus
}

// GetAcceptStatusOk returns a tuple with the AcceptStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallbackResponse) GetAcceptStatusOk() (*string, bool) {
	if o == nil || IsNil(o.AcceptStatus) {
		return nil, false
	}
	return o.AcceptStatus, true
}

// HasAcceptStatus returns a boolean if a field has been set.
func (o *CallbackResponse) HasAcceptStatus() bool {
	if o != nil && !IsNil(o.AcceptStatus) {
		return true
	}

	return false
}

// SetAcceptStatus gets a reference to the given string and assigns it to the AcceptStatus field.
func (o *CallbackResponse) SetAcceptStatus(v string) {
	o.AcceptStatus = &v
}

// GetFinalAmount returns the FinalAmount field value if set, zero value otherwise.
func (o *CallbackResponse) GetFinalAmount() float64 {
	if o == nil || IsNil(o.FinalAmount) {
		var ret float64
		return ret
	}
	return *o.FinalAmount
}

// GetFinalAmountOk returns a tuple with the FinalAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallbackResponse) GetFinalAmountOk() (*float64, bool) {
	if o == nil || IsNil(o.FinalAmount) {
		return nil, false
	}
	return o.FinalAmount, true
}

// HasFinalAmount returns a boolean if a field has been set.
func (o *CallbackResponse) HasFinalAmount() bool {
	if o != nil && !IsNil(o.FinalAmount) {
		return true
	}

	return false
}

// SetFinalAmount gets a reference to the given float64 and assigns it to the FinalAmount field.
func (o *CallbackResponse) SetFinalAmount(v float64) {
	o.FinalAmount = &v
}

func (o CallbackResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CallbackResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AcceptStatus) {
		toSerialize["accept_status"] = o.AcceptStatus
	}
	if !IsNil(o.FinalAmount) {
		toSerialize["final_amount"] = o.FinalAmount
	}
	return toSerialize, nil
}

type NullableCallbackResponse struct {
	value *CallbackResponse
	isSet bool
}

func (v NullableCallbackResponse) Get() *CallbackResponse {
	return v.value
}

func (v *NullableCallbackResponse) Set(val *CallbackResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCallbackResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCallbackResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCallbackResponse(val *CallbackResponse) *NullableCallbackResponse {
	return &NullableCallbackResponse{value: val, isSet: true}
}

func (v NullableCallbackResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCallbackResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
