/*
Octo Payment API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package octoapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PreparePaymentSuccessResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PreparePaymentSuccessResponse{}

// PreparePaymentSuccessResponse struct for PreparePaymentSuccessResponse
type PreparePaymentSuccessResponse struct {
	Error                   int32                             `form:"error" json:"error"`
	Data                    PreparePaymentSuccessResponseData `form:"data" json:"data"`
	ApiMessageForDevelopers *string                           `form:"apiMessageForDevelopers" json:"apiMessageForDevelopers,omitempty"`
	ShopTransactionId       *string                           `form:"shop_transaction_id" json:"shop_transaction_id,omitempty"`
	OctoPaymentUUID         *string                           `form:"octo_payment_UUID" json:"octo_payment_UUID,omitempty"`
	Status                  *string                           `form:"status" json:"status,omitempty"`
	OctoPayUrl              *string                           `form:"octo_pay_url" json:"octo_pay_url,omitempty"`
	RefundedSum             *float64                          `form:"refunded_sum" json:"refunded_sum,omitempty"`
	TotalSum                *float64                          `form:"total_sum" json:"total_sum,omitempty"`
}

type _PreparePaymentSuccessResponse PreparePaymentSuccessResponse

// NewPreparePaymentSuccessResponse instantiates a new PreparePaymentSuccessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPreparePaymentSuccessResponse(error_ int32, data PreparePaymentSuccessResponseData) *PreparePaymentSuccessResponse {
	this := PreparePaymentSuccessResponse{}
	this.Error = error_
	this.Data = data
	return &this
}

// NewPreparePaymentSuccessResponseWithDefaults instantiates a new PreparePaymentSuccessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPreparePaymentSuccessResponseWithDefaults() *PreparePaymentSuccessResponse {
	this := PreparePaymentSuccessResponse{}
	return &this
}

// GetError returns the Error field value
func (o *PreparePaymentSuccessResponse) GetError() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *PreparePaymentSuccessResponse) GetErrorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *PreparePaymentSuccessResponse) SetError(v int32) {
	o.Error = v
}

// GetData returns the Data field value
func (o *PreparePaymentSuccessResponse) GetData() PreparePaymentSuccessResponseData {
	if o == nil {
		var ret PreparePaymentSuccessResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PreparePaymentSuccessResponse) GetDataOk() (*PreparePaymentSuccessResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PreparePaymentSuccessResponse) SetData(v PreparePaymentSuccessResponseData) {
	o.Data = v
}

// GetApiMessageForDevelopers returns the ApiMessageForDevelopers field value if set, zero value otherwise.
func (o *PreparePaymentSuccessResponse) GetApiMessageForDevelopers() string {
	if o == nil || IsNil(o.ApiMessageForDevelopers) {
		var ret string
		return ret
	}
	return *o.ApiMessageForDevelopers
}

// GetApiMessageForDevelopersOk returns a tuple with the ApiMessageForDevelopers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentSuccessResponse) GetApiMessageForDevelopersOk() (*string, bool) {
	if o == nil || IsNil(o.ApiMessageForDevelopers) {
		return nil, false
	}
	return o.ApiMessageForDevelopers, true
}

// HasApiMessageForDevelopers returns a boolean if a field has been set.
func (o *PreparePaymentSuccessResponse) HasApiMessageForDevelopers() bool {
	if o != nil && !IsNil(o.ApiMessageForDevelopers) {
		return true
	}

	return false
}

// SetApiMessageForDevelopers gets a reference to the given string and assigns it to the ApiMessageForDevelopers field.
func (o *PreparePaymentSuccessResponse) SetApiMessageForDevelopers(v string) {
	o.ApiMessageForDevelopers = &v
}

// GetShopTransactionId returns the ShopTransactionId field value if set, zero value otherwise.
func (o *PreparePaymentSuccessResponse) GetShopTransactionId() string {
	if o == nil || IsNil(o.ShopTransactionId) {
		var ret string
		return ret
	}
	return *o.ShopTransactionId
}

// GetShopTransactionIdOk returns a tuple with the ShopTransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentSuccessResponse) GetShopTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.ShopTransactionId) {
		return nil, false
	}
	return o.ShopTransactionId, true
}

// HasShopTransactionId returns a boolean if a field has been set.
func (o *PreparePaymentSuccessResponse) HasShopTransactionId() bool {
	if o != nil && !IsNil(o.ShopTransactionId) {
		return true
	}

	return false
}

// SetShopTransactionId gets a reference to the given string and assigns it to the ShopTransactionId field.
func (o *PreparePaymentSuccessResponse) SetShopTransactionId(v string) {
	o.ShopTransactionId = &v
}

// GetOctoPaymentUUID returns the OctoPaymentUUID field value if set, zero value otherwise.
func (o *PreparePaymentSuccessResponse) GetOctoPaymentUUID() string {
	if o == nil || IsNil(o.OctoPaymentUUID) {
		var ret string
		return ret
	}
	return *o.OctoPaymentUUID
}

// GetOctoPaymentUUIDOk returns a tuple with the OctoPaymentUUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentSuccessResponse) GetOctoPaymentUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.OctoPaymentUUID) {
		return nil, false
	}
	return o.OctoPaymentUUID, true
}

// HasOctoPaymentUUID returns a boolean if a field has been set.
func (o *PreparePaymentSuccessResponse) HasOctoPaymentUUID() bool {
	if o != nil && !IsNil(o.OctoPaymentUUID) {
		return true
	}

	return false
}

// SetOctoPaymentUUID gets a reference to the given string and assigns it to the OctoPaymentUUID field.
func (o *PreparePaymentSuccessResponse) SetOctoPaymentUUID(v string) {
	o.OctoPaymentUUID = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PreparePaymentSuccessResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentSuccessResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PreparePaymentSuccessResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PreparePaymentSuccessResponse) SetStatus(v string) {
	o.Status = &v
}

// GetOctoPayUrl returns the OctoPayUrl field value if set, zero value otherwise.
func (o *PreparePaymentSuccessResponse) GetOctoPayUrl() string {
	if o == nil || IsNil(o.OctoPayUrl) {
		var ret string
		return ret
	}
	return *o.OctoPayUrl
}

// GetOctoPayUrlOk returns a tuple with the OctoPayUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentSuccessResponse) GetOctoPayUrlOk() (*string, bool) {
	if o == nil || IsNil(o.OctoPayUrl) {
		return nil, false
	}
	return o.OctoPayUrl, true
}

// HasOctoPayUrl returns a boolean if a field has been set.
func (o *PreparePaymentSuccessResponse) HasOctoPayUrl() bool {
	if o != nil && !IsNil(o.OctoPayUrl) {
		return true
	}

	return false
}

// SetOctoPayUrl gets a reference to the given string and assigns it to the OctoPayUrl field.
func (o *PreparePaymentSuccessResponse) SetOctoPayUrl(v string) {
	o.OctoPayUrl = &v
}

// GetRefundedSum returns the RefundedSum field value if set, zero value otherwise.
func (o *PreparePaymentSuccessResponse) GetRefundedSum() float64 {
	if o == nil || IsNil(o.RefundedSum) {
		var ret float64
		return ret
	}
	return *o.RefundedSum
}

// GetRefundedSumOk returns a tuple with the RefundedSum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentSuccessResponse) GetRefundedSumOk() (*float64, bool) {
	if o == nil || IsNil(o.RefundedSum) {
		return nil, false
	}
	return o.RefundedSum, true
}

// HasRefundedSum returns a boolean if a field has been set.
func (o *PreparePaymentSuccessResponse) HasRefundedSum() bool {
	if o != nil && !IsNil(o.RefundedSum) {
		return true
	}

	return false
}

// SetRefundedSum gets a reference to the given float64 and assigns it to the RefundedSum field.
func (o *PreparePaymentSuccessResponse) SetRefundedSum(v float64) {
	o.RefundedSum = &v
}

// GetTotalSum returns the TotalSum field value if set, zero value otherwise.
func (o *PreparePaymentSuccessResponse) GetTotalSum() float64 {
	if o == nil || IsNil(o.TotalSum) {
		var ret float64
		return ret
	}
	return *o.TotalSum
}

// GetTotalSumOk returns a tuple with the TotalSum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentSuccessResponse) GetTotalSumOk() (*float64, bool) {
	if o == nil || IsNil(o.TotalSum) {
		return nil, false
	}
	return o.TotalSum, true
}

// HasTotalSum returns a boolean if a field has been set.
func (o *PreparePaymentSuccessResponse) HasTotalSum() bool {
	if o != nil && !IsNil(o.TotalSum) {
		return true
	}

	return false
}

// SetTotalSum gets a reference to the given float64 and assigns it to the TotalSum field.
func (o *PreparePaymentSuccessResponse) SetTotalSum(v float64) {
	o.TotalSum = &v
}

func (o PreparePaymentSuccessResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PreparePaymentSuccessResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	toSerialize["data"] = o.Data
	if !IsNil(o.ApiMessageForDevelopers) {
		toSerialize["apiMessageForDevelopers"] = o.ApiMessageForDevelopers
	}
	if !IsNil(o.ShopTransactionId) {
		toSerialize["shop_transaction_id"] = o.ShopTransactionId
	}
	if !IsNil(o.OctoPaymentUUID) {
		toSerialize["octo_payment_UUID"] = o.OctoPaymentUUID
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.OctoPayUrl) {
		toSerialize["octo_pay_url"] = o.OctoPayUrl
	}
	if !IsNil(o.RefundedSum) {
		toSerialize["refunded_sum"] = o.RefundedSum
	}
	if !IsNil(o.TotalSum) {
		toSerialize["total_sum"] = o.TotalSum
	}
	return toSerialize, nil
}

func (o *PreparePaymentSuccessResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPreparePaymentSuccessResponse := _PreparePaymentSuccessResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPreparePaymentSuccessResponse)

	if err != nil {
		return err
	}

	*o = PreparePaymentSuccessResponse(varPreparePaymentSuccessResponse)

	return err
}

type NullablePreparePaymentSuccessResponse struct {
	value *PreparePaymentSuccessResponse
	isSet bool
}

func (v NullablePreparePaymentSuccessResponse) Get() *PreparePaymentSuccessResponse {
	return v.value
}

func (v *NullablePreparePaymentSuccessResponse) Set(val *PreparePaymentSuccessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePreparePaymentSuccessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePreparePaymentSuccessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreparePaymentSuccessResponse(val *PreparePaymentSuccessResponse) *NullablePreparePaymentSuccessResponse {
	return &NullablePreparePaymentSuccessResponse{value: val, isSet: true}
}

func (v NullablePreparePaymentSuccessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreparePaymentSuccessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
