/*
Octo Payment API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package octoapi

import (
	"encoding/json"
)

// checks if the PreparePaymentSuccessResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PreparePaymentSuccessResponseData{}

// PreparePaymentSuccessResponseData struct for PreparePaymentSuccessResponseData
type PreparePaymentSuccessResponseData struct {
	ShopTransactionId *string  `form:"shop_transaction_id" json:"shop_transaction_id,omitempty"`
	OctoPaymentUUID   *string  `form:"octo_payment_UUID" json:"octo_payment_UUID,omitempty"`
	Status            *string  `form:"status" json:"status,omitempty"`
	OctoPayUrl        *string  `form:"octo_pay_url" json:"octo_pay_url,omitempty"`
	RefundedSum       *float64 `form:"refunded_sum" json:"refunded_sum,omitempty"`
	TotalSum          *float64 `form:"total_sum" json:"total_sum,omitempty"`
}

// NewPreparePaymentSuccessResponseData instantiates a new PreparePaymentSuccessResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPreparePaymentSuccessResponseData() *PreparePaymentSuccessResponseData {
	this := PreparePaymentSuccessResponseData{}
	return &this
}

// NewPreparePaymentSuccessResponseDataWithDefaults instantiates a new PreparePaymentSuccessResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPreparePaymentSuccessResponseDataWithDefaults() *PreparePaymentSuccessResponseData {
	this := PreparePaymentSuccessResponseData{}
	return &this
}

// GetShopTransactionId returns the ShopTransactionId field value if set, zero value otherwise.
func (o *PreparePaymentSuccessResponseData) GetShopTransactionId() string {
	if o == nil || IsNil(o.ShopTransactionId) {
		var ret string
		return ret
	}
	return *o.ShopTransactionId
}

// GetShopTransactionIdOk returns a tuple with the ShopTransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentSuccessResponseData) GetShopTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.ShopTransactionId) {
		return nil, false
	}
	return o.ShopTransactionId, true
}

// HasShopTransactionId returns a boolean if a field has been set.
func (o *PreparePaymentSuccessResponseData) HasShopTransactionId() bool {
	if o != nil && !IsNil(o.ShopTransactionId) {
		return true
	}

	return false
}

// SetShopTransactionId gets a reference to the given string and assigns it to the ShopTransactionId field.
func (o *PreparePaymentSuccessResponseData) SetShopTransactionId(v string) {
	o.ShopTransactionId = &v
}

// GetOctoPaymentUUID returns the OctoPaymentUUID field value if set, zero value otherwise.
func (o *PreparePaymentSuccessResponseData) GetOctoPaymentUUID() string {
	if o == nil || IsNil(o.OctoPaymentUUID) {
		var ret string
		return ret
	}
	return *o.OctoPaymentUUID
}

// GetOctoPaymentUUIDOk returns a tuple with the OctoPaymentUUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentSuccessResponseData) GetOctoPaymentUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.OctoPaymentUUID) {
		return nil, false
	}
	return o.OctoPaymentUUID, true
}

// HasOctoPaymentUUID returns a boolean if a field has been set.
func (o *PreparePaymentSuccessResponseData) HasOctoPaymentUUID() bool {
	if o != nil && !IsNil(o.OctoPaymentUUID) {
		return true
	}

	return false
}

// SetOctoPaymentUUID gets a reference to the given string and assigns it to the OctoPaymentUUID field.
func (o *PreparePaymentSuccessResponseData) SetOctoPaymentUUID(v string) {
	o.OctoPaymentUUID = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PreparePaymentSuccessResponseData) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentSuccessResponseData) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PreparePaymentSuccessResponseData) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PreparePaymentSuccessResponseData) SetStatus(v string) {
	o.Status = &v
}

// GetOctoPayUrl returns the OctoPayUrl field value if set, zero value otherwise.
func (o *PreparePaymentSuccessResponseData) GetOctoPayUrl() string {
	if o == nil || IsNil(o.OctoPayUrl) {
		var ret string
		return ret
	}
	return *o.OctoPayUrl
}

// GetOctoPayUrlOk returns a tuple with the OctoPayUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentSuccessResponseData) GetOctoPayUrlOk() (*string, bool) {
	if o == nil || IsNil(o.OctoPayUrl) {
		return nil, false
	}
	return o.OctoPayUrl, true
}

// HasOctoPayUrl returns a boolean if a field has been set.
func (o *PreparePaymentSuccessResponseData) HasOctoPayUrl() bool {
	if o != nil && !IsNil(o.OctoPayUrl) {
		return true
	}

	return false
}

// SetOctoPayUrl gets a reference to the given string and assigns it to the OctoPayUrl field.
func (o *PreparePaymentSuccessResponseData) SetOctoPayUrl(v string) {
	o.OctoPayUrl = &v
}

// GetRefundedSum returns the RefundedSum field value if set, zero value otherwise.
func (o *PreparePaymentSuccessResponseData) GetRefundedSum() float64 {
	if o == nil || IsNil(o.RefundedSum) {
		var ret float64
		return ret
	}
	return *o.RefundedSum
}

// GetRefundedSumOk returns a tuple with the RefundedSum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentSuccessResponseData) GetRefundedSumOk() (*float64, bool) {
	if o == nil || IsNil(o.RefundedSum) {
		return nil, false
	}
	return o.RefundedSum, true
}

// HasRefundedSum returns a boolean if a field has been set.
func (o *PreparePaymentSuccessResponseData) HasRefundedSum() bool {
	if o != nil && !IsNil(o.RefundedSum) {
		return true
	}

	return false
}

// SetRefundedSum gets a reference to the given float64 and assigns it to the RefundedSum field.
func (o *PreparePaymentSuccessResponseData) SetRefundedSum(v float64) {
	o.RefundedSum = &v
}

// GetTotalSum returns the TotalSum field value if set, zero value otherwise.
func (o *PreparePaymentSuccessResponseData) GetTotalSum() float64 {
	if o == nil || IsNil(o.TotalSum) {
		var ret float64
		return ret
	}
	return *o.TotalSum
}

// GetTotalSumOk returns a tuple with the TotalSum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentSuccessResponseData) GetTotalSumOk() (*float64, bool) {
	if o == nil || IsNil(o.TotalSum) {
		return nil, false
	}
	return o.TotalSum, true
}

// HasTotalSum returns a boolean if a field has been set.
func (o *PreparePaymentSuccessResponseData) HasTotalSum() bool {
	if o != nil && !IsNil(o.TotalSum) {
		return true
	}

	return false
}

// SetTotalSum gets a reference to the given float64 and assigns it to the TotalSum field.
func (o *PreparePaymentSuccessResponseData) SetTotalSum(v float64) {
	o.TotalSum = &v
}

func (o PreparePaymentSuccessResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PreparePaymentSuccessResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ShopTransactionId) {
		toSerialize["shop_transaction_id"] = o.ShopTransactionId
	}
	if !IsNil(o.OctoPaymentUUID) {
		toSerialize["octo_payment_UUID"] = o.OctoPaymentUUID
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.OctoPayUrl) {
		toSerialize["octo_pay_url"] = o.OctoPayUrl
	}
	if !IsNil(o.RefundedSum) {
		toSerialize["refunded_sum"] = o.RefundedSum
	}
	if !IsNil(o.TotalSum) {
		toSerialize["total_sum"] = o.TotalSum
	}
	return toSerialize, nil
}

type NullablePreparePaymentSuccessResponseData struct {
	value *PreparePaymentSuccessResponseData
	isSet bool
}

func (v NullablePreparePaymentSuccessResponseData) Get() *PreparePaymentSuccessResponseData {
	return v.value
}

func (v *NullablePreparePaymentSuccessResponseData) Set(val *PreparePaymentSuccessResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullablePreparePaymentSuccessResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullablePreparePaymentSuccessResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreparePaymentSuccessResponseData(val *PreparePaymentSuccessResponseData) *NullablePreparePaymentSuccessResponseData {
	return &NullablePreparePaymentSuccessResponseData{value: val, isSet: true}
}

func (v NullablePreparePaymentSuccessResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreparePaymentSuccessResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
