/*
Octo Payment API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package octoapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the PreparePaymentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PreparePaymentRequest{}

// PreparePaymentRequest struct for PreparePaymentRequest
type PreparePaymentRequest struct {
	OctoShopId        int32           `form:"octo_shop_id" json:"octo_shop_id"`
	OctoSecret        string          `form:"octo_secret" json:"octo_secret"`
	ShopTransactionId string          `form:"shop_transaction_id" json:"shop_transaction_id"`
	AutoCapture       bool            `form:"auto_capture" json:"auto_capture"`
	Test              bool            `form:"test" json:"test"`
	InitTime          time.Time       `form:"init_time" json:"init_time"`
	UserData          *UserData       `form:"user_data" json:"user_data,omitempty"`
	TotalSum          float32         `form:"total_sum" json:"total_sum"`
	Currency          string          `form:"currency" json:"currency"`
	Description       string          `form:"description" json:"description"`
	Basket            []BasketItem    `form:"basket" json:"basket"`
	PaymentMethods    []PaymentMethod `form:"payment_methods" json:"payment_methods,omitempty"`
	TspId             *int32          `form:"tsp_id" json:"tsp_id,omitempty"`
	ReturnUrl         string          `form:"return_url" json:"return_url"`
	NotifyUrl         *string         `form:"notify_url" json:"notify_url,omitempty"`
	Language          string          `form:"language" json:"language"`
	Ttl               *int32          `form:"ttl" json:"ttl,omitempty"`
}

type _PreparePaymentRequest PreparePaymentRequest

// NewPreparePaymentRequest instantiates a new PreparePaymentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPreparePaymentRequest(octoShopId int32, octoSecret string, shopTransactionId string, autoCapture bool, test bool, initTime time.Time, totalSum float32, currency string, description string, basket []BasketItem, returnUrl string, language string) *PreparePaymentRequest {
	this := PreparePaymentRequest{}
	this.OctoShopId = octoShopId
	this.OctoSecret = octoSecret
	this.ShopTransactionId = shopTransactionId
	this.AutoCapture = autoCapture
	this.Test = test
	this.InitTime = initTime
	this.TotalSum = totalSum
	this.Currency = currency
	this.Description = description
	this.Basket = basket
	this.ReturnUrl = returnUrl
	this.Language = language
	return &this
}

// NewPreparePaymentRequestWithDefaults instantiates a new PreparePaymentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPreparePaymentRequestWithDefaults() *PreparePaymentRequest {
	this := PreparePaymentRequest{}
	var autoCapture bool = false
	this.AutoCapture = autoCapture
	return &this
}

// GetOctoShopId returns the OctoShopId field value
func (o *PreparePaymentRequest) GetOctoShopId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OctoShopId
}

// GetOctoShopIdOk returns a tuple with the OctoShopId field value
// and a boolean to check if the value has been set.
func (o *PreparePaymentRequest) GetOctoShopIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OctoShopId, true
}

// SetOctoShopId sets field value
func (o *PreparePaymentRequest) SetOctoShopId(v int32) {
	o.OctoShopId = v
}

// GetOctoSecret returns the OctoSecret field value
func (o *PreparePaymentRequest) GetOctoSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OctoSecret
}

// GetOctoSecretOk returns a tuple with the OctoSecret field value
// and a boolean to check if the value has been set.
func (o *PreparePaymentRequest) GetOctoSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OctoSecret, true
}

// SetOctoSecret sets field value
func (o *PreparePaymentRequest) SetOctoSecret(v string) {
	o.OctoSecret = v
}

// GetShopTransactionId returns the ShopTransactionId field value
func (o *PreparePaymentRequest) GetShopTransactionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShopTransactionId
}

// GetShopTransactionIdOk returns a tuple with the ShopTransactionId field value
// and a boolean to check if the value has been set.
func (o *PreparePaymentRequest) GetShopTransactionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShopTransactionId, true
}

// SetShopTransactionId sets field value
func (o *PreparePaymentRequest) SetShopTransactionId(v string) {
	o.ShopTransactionId = v
}

// GetAutoCapture returns the AutoCapture field value
func (o *PreparePaymentRequest) GetAutoCapture() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AutoCapture
}

// GetAutoCaptureOk returns a tuple with the AutoCapture field value
// and a boolean to check if the value has been set.
func (o *PreparePaymentRequest) GetAutoCaptureOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AutoCapture, true
}

// SetAutoCapture sets field value
func (o *PreparePaymentRequest) SetAutoCapture(v bool) {
	o.AutoCapture = v
}

// GetTest returns the Test field value
func (o *PreparePaymentRequest) GetTest() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Test
}

// GetTestOk returns a tuple with the Test field value
// and a boolean to check if the value has been set.
func (o *PreparePaymentRequest) GetTestOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Test, true
}

// SetTest sets field value
func (o *PreparePaymentRequest) SetTest(v bool) {
	o.Test = v
}

// GetInitTime returns the InitTime field value
func (o *PreparePaymentRequest) GetInitTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.InitTime
}

// GetInitTimeOk returns a tuple with the InitTime field value
// and a boolean to check if the value has been set.
func (o *PreparePaymentRequest) GetInitTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InitTime, true
}

// SetInitTime sets field value
func (o *PreparePaymentRequest) SetInitTime(v time.Time) {
	o.InitTime = v
}

// GetUserData returns the UserData field value if set, zero value otherwise.
func (o *PreparePaymentRequest) GetUserData() UserData {
	if o == nil || IsNil(o.UserData) {
		var ret UserData
		return ret
	}
	return *o.UserData
}

// GetUserDataOk returns a tuple with the UserData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentRequest) GetUserDataOk() (*UserData, bool) {
	if o == nil || IsNil(o.UserData) {
		return nil, false
	}
	return o.UserData, true
}

// HasUserData returns a boolean if a field has been set.
func (o *PreparePaymentRequest) HasUserData() bool {
	if o != nil && !IsNil(o.UserData) {
		return true
	}

	return false
}

// SetUserData gets a reference to the given UserData and assigns it to the UserData field.
func (o *PreparePaymentRequest) SetUserData(v UserData) {
	o.UserData = &v
}

// GetTotalSum returns the TotalSum field value
func (o *PreparePaymentRequest) GetTotalSum() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalSum
}

// GetTotalSumOk returns a tuple with the TotalSum field value
// and a boolean to check if the value has been set.
func (o *PreparePaymentRequest) GetTotalSumOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalSum, true
}

// SetTotalSum sets field value
func (o *PreparePaymentRequest) SetTotalSum(v float32) {
	o.TotalSum = v
}

// GetCurrency returns the Currency field value
func (o *PreparePaymentRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *PreparePaymentRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *PreparePaymentRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetDescription returns the Description field value
func (o *PreparePaymentRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *PreparePaymentRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *PreparePaymentRequest) SetDescription(v string) {
	o.Description = v
}

// GetBasket returns the Basket field value
func (o *PreparePaymentRequest) GetBasket() []BasketItem {
	if o == nil {
		var ret []BasketItem
		return ret
	}

	return o.Basket
}

// GetBasketOk returns a tuple with the Basket field value
// and a boolean to check if the value has been set.
func (o *PreparePaymentRequest) GetBasketOk() ([]BasketItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Basket, true
}

// SetBasket sets field value
func (o *PreparePaymentRequest) SetBasket(v []BasketItem) {
	o.Basket = v
}

// GetPaymentMethods returns the PaymentMethods field value if set, zero value otherwise.
func (o *PreparePaymentRequest) GetPaymentMethods() []PaymentMethod {
	if o == nil || IsNil(o.PaymentMethods) {
		var ret []PaymentMethod
		return ret
	}
	return o.PaymentMethods
}

// GetPaymentMethodsOk returns a tuple with the PaymentMethods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentRequest) GetPaymentMethodsOk() ([]PaymentMethod, bool) {
	if o == nil || IsNil(o.PaymentMethods) {
		return nil, false
	}
	return o.PaymentMethods, true
}

// HasPaymentMethods returns a boolean if a field has been set.
func (o *PreparePaymentRequest) HasPaymentMethods() bool {
	if o != nil && !IsNil(o.PaymentMethods) {
		return true
	}

	return false
}

// SetPaymentMethods gets a reference to the given []PaymentMethod and assigns it to the PaymentMethods field.
func (o *PreparePaymentRequest) SetPaymentMethods(v []PaymentMethod) {
	o.PaymentMethods = v
}

// GetTspId returns the TspId field value if set, zero value otherwise.
func (o *PreparePaymentRequest) GetTspId() int32 {
	if o == nil || IsNil(o.TspId) {
		var ret int32
		return ret
	}
	return *o.TspId
}

// GetTspIdOk returns a tuple with the TspId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentRequest) GetTspIdOk() (*int32, bool) {
	if o == nil || IsNil(o.TspId) {
		return nil, false
	}
	return o.TspId, true
}

// HasTspId returns a boolean if a field has been set.
func (o *PreparePaymentRequest) HasTspId() bool {
	if o != nil && !IsNil(o.TspId) {
		return true
	}

	return false
}

// SetTspId gets a reference to the given int32 and assigns it to the TspId field.
func (o *PreparePaymentRequest) SetTspId(v int32) {
	o.TspId = &v
}

// GetReturnUrl returns the ReturnUrl field value
func (o *PreparePaymentRequest) GetReturnUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReturnUrl
}

// GetReturnUrlOk returns a tuple with the ReturnUrl field value
// and a boolean to check if the value has been set.
func (o *PreparePaymentRequest) GetReturnUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReturnUrl, true
}

// SetReturnUrl sets field value
func (o *PreparePaymentRequest) SetReturnUrl(v string) {
	o.ReturnUrl = v
}

// GetNotifyUrl returns the NotifyUrl field value if set, zero value otherwise.
func (o *PreparePaymentRequest) GetNotifyUrl() string {
	if o == nil || IsNil(o.NotifyUrl) {
		var ret string
		return ret
	}
	return *o.NotifyUrl
}

// GetNotifyUrlOk returns a tuple with the NotifyUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentRequest) GetNotifyUrlOk() (*string, bool) {
	if o == nil || IsNil(o.NotifyUrl) {
		return nil, false
	}
	return o.NotifyUrl, true
}

// HasNotifyUrl returns a boolean if a field has been set.
func (o *PreparePaymentRequest) HasNotifyUrl() bool {
	if o != nil && !IsNil(o.NotifyUrl) {
		return true
	}

	return false
}

// SetNotifyUrl gets a reference to the given string and assigns it to the NotifyUrl field.
func (o *PreparePaymentRequest) SetNotifyUrl(v string) {
	o.NotifyUrl = &v
}

// GetLanguage returns the Language field value
func (o *PreparePaymentRequest) GetLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Language
}

// GetLanguageOk returns a tuple with the Language field value
// and a boolean to check if the value has been set.
func (o *PreparePaymentRequest) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Language, true
}

// SetLanguage sets field value
func (o *PreparePaymentRequest) SetLanguage(v string) {
	o.Language = v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *PreparePaymentRequest) GetTtl() int32 {
	if o == nil || IsNil(o.Ttl) {
		var ret int32
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreparePaymentRequest) GetTtlOk() (*int32, bool) {
	if o == nil || IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *PreparePaymentRequest) HasTtl() bool {
	if o != nil && !IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given int32 and assigns it to the Ttl field.
func (o *PreparePaymentRequest) SetTtl(v int32) {
	o.Ttl = &v
}

func (o PreparePaymentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PreparePaymentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["octo_shop_id"] = o.OctoShopId
	toSerialize["octo_secret"] = o.OctoSecret
	toSerialize["shop_transaction_id"] = o.ShopTransactionId
	toSerialize["auto_capture"] = o.AutoCapture
	toSerialize["test"] = o.Test
	toSerialize["init_time"] = o.InitTime
	if !IsNil(o.UserData) {
		toSerialize["user_data"] = o.UserData
	}
	toSerialize["total_sum"] = o.TotalSum
	toSerialize["currency"] = o.Currency
	toSerialize["description"] = o.Description
	toSerialize["basket"] = o.Basket
	if !IsNil(o.PaymentMethods) {
		toSerialize["payment_methods"] = o.PaymentMethods
	}
	if !IsNil(o.TspId) {
		toSerialize["tsp_id"] = o.TspId
	}
	toSerialize["return_url"] = o.ReturnUrl
	if !IsNil(o.NotifyUrl) {
		toSerialize["notify_url"] = o.NotifyUrl
	}
	toSerialize["language"] = o.Language
	if !IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	return toSerialize, nil
}

func (o *PreparePaymentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"octo_shop_id",
		"octo_secret",
		"shop_transaction_id",
		"auto_capture",
		"test",
		"init_time",
		"total_sum",
		"currency",
		"description",
		"basket",
		"return_url",
		"language",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPreparePaymentRequest := _PreparePaymentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPreparePaymentRequest)

	if err != nil {
		return err
	}

	*o = PreparePaymentRequest(varPreparePaymentRequest)

	return err
}

type NullablePreparePaymentRequest struct {
	value *PreparePaymentRequest
	isSet bool
}

func (v NullablePreparePaymentRequest) Get() *PreparePaymentRequest {
	return v.value
}

func (v *NullablePreparePaymentRequest) Set(val *PreparePaymentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePreparePaymentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePreparePaymentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreparePaymentRequest(val *PreparePaymentRequest) *NullablePreparePaymentRequest {
	return &NullablePreparePaymentRequest{value: val, isSet: true}
}

func (v NullablePreparePaymentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreparePaymentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
